<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Arrowgene.Ddon.Cli</RootNamespace>
        <Title>Dragons Dogma Online - Command Line Interface</Title>
        <Company>Ddon Team</Company>
        <Product>Ddon.Cli</Product>
        <Version>$(Version)</Version>
        <Copyright>Copyright © 2019-2026 DDON Team</Copyright>
        <LangVersion>13</LangVersion>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
      <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
      <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
    </PropertyGroup>
    <Import Project="./../SetSourceRevision.targets" />
    <ItemGroup>
        <ProjectReference Include="..\Arrowgene.Ddon.Client\Arrowgene.Ddon.Client.csproj" />
        <ProjectReference Include="..\Arrowgene.Ddon.GameServer\Arrowgene.Ddon.GameServer.csproj" />
        <ProjectReference Include="..\Arrowgene.Ddon.LoginServer\Arrowgene.Ddon.LoginServer.csproj" />
        <ProjectReference Include="..\Arrowgene.Ddon.Metrics\Arrowgene.Ddon.Metrics.csproj" />
        <ProjectReference Include="..\Arrowgene.Ddon.Rpc.Web\Arrowgene.Ddon.Rpc.Web.csproj" />
        <ProjectReference Include="..\Arrowgene.Ddon.Server\Arrowgene.Ddon.Server.csproj" />
        <ProjectReference Include="..\Arrowgene.Ddon.WebServer\Arrowgene.Ddon.WebServer.csproj" />
        <ProjectReference Include="..\Arrowgene.Ddon.Scripts\Arrowgene.Ddon.Scripts.csproj" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="Arrowgene.Logging" Version="1.2.1" />
    </ItemGroup>
    <ItemGroup>
        <RuntimeHostConfigurationOption Include="System.GC.Server" Value="true" />
    </ItemGroup>
    <ItemGroup>
      <None Include="bin\Debug\net10.0\Files\www\dist\index.html" />
      <None Include="bin\Debug\net10.0\Files\www\dist\metrics\game\duration_histogram.json" />
      <None Include="bin\Debug\net10.0\Files\www\dist\metrics\game\handlers.json" />
      <None Include="bin\Debug\net10.0\Files\www\dist\metrics\game\timeseries.json" />
      <None Include="bin\Debug\net10.0\Files\www\dist\metrics\login\duration_histogram.json" />
      <None Include="bin\Debug\net10.0\Files\www\dist\metrics\login\handlers.json" />
      <None Include="bin\Debug\net10.0\Files\www\dist\metrics\login\timeseries.json" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\@observablehq\plot@0.6.17\7c43807f.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\binary-search-bounds@2.0.5\cbf6ba23.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\d3-array@3.2.4\e93ca09f.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\d3-axis@3.0.0\0f2de24d.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\d3-brush@3.0.0\65eb105b.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\d3-chord@3.0.1\7ef8fb2e.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\d3-color@3.1.0\aeb57b94.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\d3-contour@4.0.2\1d2aed74.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\d3-delaunay@6.0.4\5ced1d52.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\d3-dispatch@3.0.1\9ba9c7f3.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\d3-drag@3.0.0\4202580c.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\d3-dsv@3.0.1\9cffc2bd.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\d3-ease@3.0.1\cdd7e898.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\d3-fetch@3.0.1\b4e2ad9a.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\d3-force@3.0.0\5e804d15.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\d3-format@3.1.2\3785bf2d.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\d3-geo@3.1.1\40599fb3.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\d3-hierarchy@3.1.2\e49e792c.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\d3-interpolate@3.0.1\8d1e5425.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\d3-path@3.1.0\20d3f133.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\d3-polygon@3.0.1\7553081f.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\d3-quadtree@3.0.1\0dfd751c.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\d3-random@3.0.1\3c90ee06.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\d3-scale-chromatic@3.1.0\ba24c2e7.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\d3-scale@4.0.2\720b7f0a.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\d3-selection@3.0.0\4d94e5b7.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\d3-shape@3.2.0\6d3a6726.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\d3-time-format@4.1.0\07c9626f.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\d3-time@3.1.0\9f03c579.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\d3-timer@3.0.1\b58a267d.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\d3-transition@3.0.1\004da2ac.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\d3-zoom@3.0.0\b5786b3f.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\d3@7.9.0\e324157d.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\delaunator@5.0.1\02d43215.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\htl@0.3.1\72f4716c.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\internmap@2.0.3\e08981d9.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\interval-tree-1d@1.0.4\53fe8176.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\isoformat@0.2.1\18cbf477.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_npm\robust-predicates@3.0.2\aa00730b.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_observablehq\client.e18424d4.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_observablehq\runtime.607a8173.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_observablehq\stdlib.277aeab8.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_observablehq\stdlib\inputs.31cd1366.js" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_observablehq\stdlib\inputs.f7bf0e12.css" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_observablehq\theme-air,near-midnight,alt,wide.9b64840a.css" />
      <None Include="bin\Debug\net10.0\Files\www\dist\_observablehq\theme-near-midnight,alt,wide,wide.f85da195.css" />
    </ItemGroup>
    <ItemGroup>
      <Folder Include="bin\Debug\" />
      <Folder Include="bin\Debug\net10.0\Files\www\" />
    </ItemGroup>
</Project>
