
namespace Arrowgene.Ddon.Shared.Model
    
{
    public class ArisenCsv
    {
        public JobId Job { get; set; }
        public uint Lv { get; set; }
        public uint HP { get; set; }
        public uint Stamina { get; set; }
        public byte RevivePoint { get; set; }
        public uint MaxHP { get; set; }
        public uint MaxStamina { get; set; }
        public uint WhiteHP { get; set; }
        public uint GainHP { get; set; }
        public uint GainStamina { get; set; }
        public uint GainAttack { get; set; }
        public uint GainDefense { get; set; }
        public uint GainMagicAttack { get; set; }
        public uint GainMagicDefense { get; set; }
        public uint Cs1MpId { get; set; }
        public byte Cs1MpLv { get; set; }
        public uint Cs2MpId { get; set; }
        public byte Cs2MpLv { get; set; }
        public uint Cs3MpId { get; set; }
        public byte Cs3MpLv { get; set; }
        public uint Cs4MpId { get; set; }
        public byte Cs4MpLv { get; set; }
        public uint Cs1SpId { get; set; }
        public byte Cs1SpLv { get; set; }
        public uint Cs2SpId { get; set; }
        public byte Cs2SpLv { get; set; }
        public uint Cs3SpId { get; set; }
        public byte Cs3SpLv { get; set; }
        public uint Cs4SpId { get; set; }
        public byte Cs4SpLv { get; set; }
        public JobId Ab1Jb { get; set; }
        public uint Ab1Id { get; set; }
        public byte Ab1Lv { get; set; }
        public JobId Ab2Jb { get; set; }
        public uint Ab2Id { get; set; }
        public byte Ab2Lv { get; set; }
        public JobId Ab3Jb { get; set; }
        public uint Ab3Id { get; set; }
        public byte Ab3Lv { get; set; }
        public JobId Ab4Jb { get; set; }
        public uint Ab4Id { get; set; }
        public byte Ab4Lv { get; set; }
        public JobId Ab5Jb { get; set; }
        public uint Ab5Id { get; set; }
        public byte Ab5Lv { get; set; }
        public JobId Ab6Jb { get; set; }
        public uint Ab6Id { get; set; }
        public byte Ab6Lv { get; set; }
        public JobId Ab7Jb { get; set; }
        public uint Ab7Id { get; set; }
        public byte Ab7Lv { get; set; }
        public JobId Ab8Jb { get; set; }
        public uint Ab8Id { get; set; }
        public byte Ab8Lv { get; set; }
        public JobId Ab9Jb { get; set; }
        public uint Ab9Id { get; set; }
        public byte Ab9Lv { get; set; }
        public JobId Ab10Jb { get; set; }
        public uint Ab10Id { get; set; }
        public byte Ab10Lv { get; set; }
        public ushort PAtk { get; set; }
        public ushort PDef { get; set; }
        public ushort MAtk { get; set; }
        public ushort MDef { get; set; }
        public uint PrimaryWeapon { get; set; }
        public byte PrimaryWeaponColour { get; set; }
        public uint PWCrest1 { get; set; }
        public byte PWC1Add1 { get; set; }
        public byte PWC1Add2 { get; set; }
        public uint PWCrest2 { get; set; }
        public byte PWC2Add1 { get; set; }
        public byte PWC2Add2 { get; set; }
        public uint PWCrest3 { get; set; }
        public byte PWC3Add1 { get; set; }
        public byte PWC3Add2 { get; set; }
        public uint PWCrest4 { get; set; }
        public byte PWC4Add1 { get; set; }
        public byte PWC4Add2 { get; set; }
        public uint SecondaryWeapon { get; set; }
        public byte SecondaryWeaponColour { get; set; }
        public uint Head { get; set; }
        public byte HeadColour { get; set; }
        public uint HeadCrest1 { get; set; }
        public byte HC1Add1 { get; set; }
        public byte HC1Add2 { get; set; }
        public uint HeadCrest2 { get; set; }
        public byte HC2Add1 { get; set; }
        public byte HC2Add2 { get; set; }
        public uint HeadCrest3 { get; set; }
        public byte HC3Add1 { get; set; }
        public byte HC3Add2 { get; set; }
        public uint Body { get; set; }
        public byte BodyColour { get; set; }
        public uint BodyCrest1 { get; set; }
        public byte BC1Add1 { get; set; }
        public byte BC1Add2 { get; set; }
        public uint BodyCrest2 { get; set; }
        public byte BC2Add1 { get; set; }
        public byte BC2Add2 { get; set; }
        public uint BodyCrest3 { get; set; }
        public byte BC3Add1 { get; set; }
        public byte BC3Add2 { get; set; }
        public uint BodyCrest4 { get; set; }
        public byte BC4Add1 { get; set; }
        public byte BC4Add2 { get; set; }
        public uint Clothing { get; set; }
        public byte ClothingColour { get; set; }
        public uint Arm { get; set; }
        public byte ArmColour { get; set; }
        public uint ArmCrest1 { get; set; }
        public byte AC1Add1 { get; set; }
        public byte AC1Add2 { get; set; }
        public uint ArmCrest2 { get; set; }
        public byte AC2Add1 { get; set; }
        public byte AC2Add2 { get; set; }
        public uint ArmCrest3 { get; set; }
        public byte AC3Add1 { get; set; }
        public byte AC3Add2 { get; set; }
        public uint Leg { get; set; }
        public byte LegColour { get; set; }
        public uint LegCrest1 { get; set; }
        public byte LC1Add1 { get; set; }
        public byte LC1Add2 { get; set; }
        public uint LegCrest2 { get; set; }
        public byte LC2Add1 { get; set; }
        public byte LC2Add2 { get; set; }
        public uint LegCrest3 { get; set; }
        public byte LC3Add1 { get; set; }
        public byte LC3Add2 { get; set; }
        public uint Legwear { get; set; }
        public byte LegwearColour { get; set; }
        public uint Overwear { get; set; }
        public byte OverwearColour { get; set; }
        public uint Lantern { get; set; }
        public bool DisplayHelmet { get; set; }
        public bool DisplayLantern { get; set; }
        public uint VPrimaryWeapon { get; set; }
        public byte VPrimaryWeaponColour { get; set; }
        public uint VSecondaryWeapon { get; set; }
        public byte VSecondaryWeaponColour { get; set; }
        public uint VHead { get; set; }
        public byte VHeadColour { get; set; }
        public uint VBody { get; set; }
        public byte VBodyColour { get; set; }
        public uint VClothing { get; set; }
        public byte VClothingColour { get; set; }
        public uint VArm { get; set; }
        public byte VArmColour { get; set; }
        public uint VLeg { get; set; }
        public byte VLegColour { get; set; }
        public uint VLegwear { get; set; }
        public byte VLegwearColour { get; set; }
        public uint VOverwear { get; set; }
        public byte VOverwearColour { get; set; }
        public uint ClassItem1 { get; set; }
        public uint ClassItem2 { get; set; }
        public uint Jewelry1 { get; set; }
        public uint J1Crest1 { get; set; }
        public byte J1C1Add1 { get; set; }
        public byte J1C1Add2 { get; set; }
        public uint J1Crest2 { get; set; }
        public byte J1C2Add1 { get; set; }
        public byte J1C2Add2 { get; set; }
        public uint J1Crest3 { get; set; }
        public byte J1C3Add1 { get; set; }
        public byte J1C3Add2 { get; set; }
        public uint J1Crest4 { get; set; }
        public byte J1C4Add1 { get; set; }
        public byte J1C4Add2 { get; set; }
        public uint Jewelry2 { get; set; }
        public uint J2Crest1 { get; set; }
        public byte J2C1Add1 { get; set; }
        public byte J2C1Add2 { get; set; }
        public uint J2Crest2 { get; set; }
        public byte J2C2Add1 { get; set; }
        public byte J2C2Add2 { get; set; }
        public uint J2Crest3 { get; set; }
        public byte J2C3Add1 { get; set; }
        public byte J2C3Add2 { get; set; }
        public uint J2Crest4 { get; set; }
        public byte J2C4Add1 { get; set; }
        public byte J2C4Add2 { get; set; }
        public uint Jewelry3 { get; set; }
        public uint J3Crest1 { get; set; }
        public byte J3C1Add1 { get; set; }
        public byte J3C1Add2 { get; set; }
        public uint J3Crest2 { get; set; }
        public byte J3C2Add1 { get; set; }
        public byte J3C2Add2 { get; set; }
        public uint J3Crest3 { get; set; }
        public byte J3C3Add1 { get; set; }
        public byte J3C3Add2 { get; set; }
        public uint J3Crest4 { get; set; }
        public byte J3C4Add1 { get; set; }
        public byte J3C4Add2 { get; set; }
        public uint Jewelry4 { get; set; }
        public uint J4Crest1 { get; set; }
        public byte J4C1Add1 { get; set; }
        public byte J4C1Add2 { get; set; }
        public uint J4Crest2 { get; set; }
        public byte J4C2Add1 { get; set; }
        public byte J4C2Add2 { get; set; }
        public uint J4Crest3 { get; set; }
        public byte J4C3Add1 { get; set; }
        public byte J4C3Add2 { get; set; }
        public uint J4Crest4 { get; set; }
        public byte J4C4Add1 { get; set; }
        public byte J4C4Add2 { get; set; }
        public uint Jewelry5 { get; set; }
        public uint J5Crest1 { get; set; }
        public byte J5C1Add1 { get; set; }
        public byte J5C1Add2 { get; set; }
        public uint J5Crest2 { get; set; }
        public byte J5C2Add1 { get; set; }
        public byte J5C2Add2 { get; set; }
        public uint J5Crest3 { get; set; }
        public byte J5C3Add1 { get; set; }
        public byte J5C3Add2 { get; set; }
        public uint J5Crest4 { get; set; }
        public byte J5C4Add1 { get; set; }
        public byte J5C4Add2 { get; set; }
        public uint Exp { get; set; }
        public uint JobPoint { get; set; }
        public ushort Strength { get; set; }
        public ushort DownPower { get; set; }
        public ushort ShakePower { get; set; }
        public ushort StunPower { get; set; }
        public ushort Consitution { get; set; }
        public ushort Guts { get; set; }
        public byte FireResist { get; set; }
        public byte IceResist { get; set; }
        public byte ThunderResist { get; set; }
        public byte HolyResist { get; set; }
        public byte DarkResist { get; set; }
        public byte SpreadResist { get; set; }
        public byte FreezeResist { get; set; }
        public byte ShockResist { get; set; }
        public byte AbsorbResist { get; set; }
        public byte DarkElmResist { get; set; }
        public byte PoisonResist { get; set; }
        public byte SlowResist { get; set; }
        public byte SleepResist { get; set; }
        public byte StunResist { get; set; }
        public byte WetResist { get; set; }
        public byte OilResist { get; set; }
        public byte SealResist { get; set; }
        public byte CurseResist { get; set; }
        public byte SoftResist { get; set; }
        public byte StoneResist { get; set; }
        public byte GoldResist { get; set; }
        public byte FireReduceResist { get; set; }
        public byte IceReduceResist { get; set; }
        public byte ThunderReduceResist { get; set; }
        public byte HolyReduceResist { get; set; }
        public byte DarkReduceResist { get; set; }
        public byte AtkDownResist { get; set; }
        public byte DefDownResist { get; set; }
        public byte MAtkDownResist { get; set; }
        public byte MDefDownResist { get; set; }
        public uint NormalSkill1A { get; set; }
        public uint NormalSkill1B { get; set; }
        public uint NormalSkill2A { get; set; }
        public uint NormalSkill2B { get; set; }
        public uint NormalSkill3A { get; set; }
        public uint NormalSkill3B { get; set; }
    }
}
