using System.Collections.Generic;

namespace Arrowgene.Ddon.Shared.Model
{
    public static class EnemyIdExtension
    {
        private static readonly Dictionary<EnemyId, HmPresetId> HmPresetMap = new Dictionary<EnemyId, HmPresetId>()
        {
            [EnemyId.RogueFighter] = HmPresetId.RogueFighter,
            [EnemyId.RogueSeeker] = HmPresetId.RogueSeeker,
            [EnemyId.RogueHunter] = HmPresetId.RogueHunter,
            [EnemyId.RogueHealer] = HmPresetId.RogueHealer,
            [EnemyId.RogueDefender] = HmPresetId.RogueDefender,
            [EnemyId.RogueMage] = HmPresetId.RogueMage,
            [EnemyId.RogueWarrior] = HmPresetId.RogueWarrior,
            [EnemyId.BandedFighter] = HmPresetId.BandedFighter,
            [EnemyId.BandedSeeker] = HmPresetId.BandedSeeker,
            [EnemyId.BandedHunter] = HmPresetId.BandedHunter,
            [EnemyId.BandedHealer] = HmPresetId.BandedHealer,
            [EnemyId.BandedDefender] = HmPresetId.BandedDefender,
            [EnemyId.BandedMage] = HmPresetId.BandedMage,
            [EnemyId.BandedWarrior] = HmPresetId.BandedWarrior,
            [EnemyId.MerganFighter] = HmPresetId.MerganFighter,
            [EnemyId.MerganSeeker] = HmPresetId.MerganSeeker,
            [EnemyId.MerganHunter] = HmPresetId.MerganHunter,
            [EnemyId.MerganHealer] = HmPresetId.MerganHealer,
            [EnemyId.MerganDefender] = HmPresetId.MerganDefender,
            [EnemyId.MerganMage] = HmPresetId.MerganMage,
            [EnemyId.MerganWarrior] = HmPresetId.MerganWarrior,
            [EnemyId.MerganElementArcher] = HmPresetId.MerganElementalArcher,
            [EnemyId.MistFighter] = HmPresetId.MistFighter,
            [EnemyId.MistHunter] = HmPresetId.MistHunter,
            [EnemyId.MistPriest] = HmPresetId.MistPriest,
            [EnemyId.MistSorcerer] = HmPresetId.MistSorcerer,
            [EnemyId.MistWarrior] = HmPresetId.MistWarrior,
            [EnemyId.Iris] = HmPresetId.Iris,
            [EnemyId.DiamantesHuman] = HmPresetId.DiamantesHuman,
            [EnemyId.Leo] = HmPresetId.LeoS1,
            [EnemyId.HoodedIris] = HmPresetId.HoodedIris,
            [EnemyId.FormerCommanderLeoFinalBoss] = HmPresetId.LeoS3,
            [EnemyId.PawnFighter] = HmPresetId.PawnFighter,
            [EnemyId.PawnSeeker] = HmPresetId.PawnSeeker,
            [EnemyId.PawnHunter] = HmPresetId.PawnHunter,
            [EnemyId.PawnHealer] = HmPresetId.PawnHealer,
            [EnemyId.PawnDefender] = HmPresetId.PawnDefender,
            [EnemyId.PawnMage] = HmPresetId.PawnMage,
            [EnemyId.PawnWarrior] = HmPresetId.PawnWarrior,
            [EnemyId.PawnElementArcher] = HmPresetId.PawnElementalArcher,
            [EnemyId.PhindymianFighter] = HmPresetId.PhindymianFighter,
            [EnemyId.PhindymianSeeker] = HmPresetId.PhindymianSeeker,
            [EnemyId.PhindymianHunter] = HmPresetId.PhindymianHunter,
            [EnemyId.PhindymianPriest] = HmPresetId.PhindymianPriest,
            [EnemyId.PhindymianDefender] = HmPresetId.PhindymianDefender,
            [EnemyId.PhindymianSorcerer] = HmPresetId.PhindymianSorcerer,
            [EnemyId.PhindymianWarrior] = HmPresetId.PhindymianWarrior,
            [EnemyId.PhindymianElementArcher] = HmPresetId.PhindymianElementalArcher,
            [EnemyId.ScarletFighter] = HmPresetId.ScarletFighter,
            [EnemyId.ScarletSeeker] = HmPresetId.ScarletSeeker,
            [EnemyId.ScarletHunter] = HmPresetId.ScarletHunter,
            [EnemyId.ScarletHealer] = HmPresetId.ScarletHealer,
            [EnemyId.ScarletDefender] = HmPresetId.ScarletDefender,
            [EnemyId.ScarletMage] = HmPresetId.ScarletMage,
            [EnemyId.ScarletWarrior] = HmPresetId.ScarletWarrior,
            [EnemyId.MegadoGuardFighter] = HmPresetId.MegadoGuardFighter,
            [EnemyId.MegadoGuardSeeker] = HmPresetId.MegadoGuardSeeker,
            [EnemyId.MegadoGuardHunter] = HmPresetId.MegadoGuardHunter,
            [EnemyId.MegadoGuardWarrior] = HmPresetId.MegadoGuardWarrior,
        };

        public static readonly Dictionary<EnemyId, EnemyUIId> NameMap = new Dictionary<EnemyId, EnemyUIId>()
        {
            { EnemyId.Goblin , EnemyUIId.Goblin },
            { EnemyId.GoblinFighter0 , EnemyUIId.GoblinFighter },
            { EnemyId.ShieldGoblin , EnemyUIId.ShieldGoblin },
            { EnemyId.SlingGoblinRock , EnemyUIId.SlingGoblin },
            { EnemyId.GoblinLeader , EnemyUIId.GoblinLeader },
            { EnemyId.SlingGoblinTorch , EnemyUIId.SlingGoblin },
            { EnemyId.Hobgoblin , EnemyUIId.Hobgoblin },
            { EnemyId.HobgoblinFighter , EnemyUIId.HobgoblinFighter },
            { EnemyId.SlingHobgoblinOilFlask , EnemyUIId.SlingHobgoblin },
            { EnemyId.HobgoblinLeader , EnemyUIId.HobgoblinLeader },
            { EnemyId.SlingHobgoblinTorch , EnemyUIId.SlingHobgoblin },
            { EnemyId.GrimGoblin , EnemyUIId.GrimGoblin },
            { EnemyId.GrimGoblinFighter , EnemyUIId.GrimGoblinFighter },
            { EnemyId.SlingGrimGoblinOilFlask , EnemyUIId.SlingGrimGoblin },
            { EnemyId.GrimGoblinLeader , EnemyUIId.GrimGoblinLeader },
            { EnemyId.GreaterGoblinSword , EnemyUIId.GreaterGoblin },
            { EnemyId.GreaterGoblinTorch , EnemyUIId.GreaterGoblin },
            { EnemyId.GoblinShaman , EnemyUIId.GoblinShaman },
            { EnemyId.GoblinAidShaman , EnemyUIId.GoblinAidShaman },
            { EnemyId.Pixie , EnemyUIId.Pixie },
            { EnemyId.PixieBiff , EnemyUIId.PixieBiff },
            { EnemyId.PixieDin , EnemyUIId.PixieDin },
            { EnemyId.PixiePow , EnemyUIId.PixiePow },
            { EnemyId.PixieJabber , EnemyUIId.PixieJabber },
            { EnemyId.InfectedHobgoblin , EnemyUIId.InfectedHobgoblin },
            { EnemyId.InfectedHobgoblinFighter , EnemyUIId.InfectedHobgoblinFighter },
            { EnemyId.InfectedSlingHobgoblin , EnemyUIId.InfectedSlingHobgoblin },
            { EnemyId.SeverelyInfectedPixie , EnemyUIId.SeverelyInfectedPixie },
            { EnemyId.SeverelyInfectedPixieClub , EnemyUIId.SeverelyInfectedPixie },
            { EnemyId.SeverelyInfectedPixieCorruptionSeeds , EnemyUIId.SeverelyInfectedPixie },
            { EnemyId.GoblinHorn , EnemyUIId.Goblin },
            { EnemyId.HighPixieBiff , EnemyUIId.HighPixieBiff },
            { EnemyId.HighPixieZolda , EnemyUIId.HighPixieZolda },
            { EnemyId.HighPixiePow , EnemyUIId.HighPixiePow },
            { EnemyId.PixieKing , EnemyUIId.PixieKing },
            { EnemyId.Wolf , EnemyUIId.Wolf },
            { EnemyId.Direwolf , EnemyUIId.Direwolf },
            { EnemyId.Hellhound , EnemyUIId.Hellhound },
            { EnemyId.Warg , EnemyUIId.Warg },
            { EnemyId.Grimwarg , EnemyUIId.Grimwarg },
            { EnemyId.ShadowWolf , EnemyUIId.ShadowWolf },
            { EnemyId.AlchemizedWolf , EnemyUIId.AlchemizedWolf },
            { EnemyId.DamnedWolf , EnemyUIId.DamnedWolf },
            { EnemyId.InfectedDirewolf , EnemyUIId.InfectedDirewolf },
            { EnemyId.GreenGuardian , EnemyUIId.GreenGuardian },
            { EnemyId.BoltGrimwarg , EnemyUIId.BoltGrimwarg },
            { EnemyId.BlazeWolf , EnemyUIId.BlazeWolf },
            { EnemyId.SeverelyInfectedWarg , EnemyUIId.SeverelyInfectedWarg },
            { EnemyId.SkeletonWarg , EnemyUIId.SkeletonWarg },
            { EnemyId.WarReadyGrimwargLightArmor , EnemyUIId.WarReadyGrimwarg },
            { EnemyId.Valefar , EnemyUIId.Valefar },
            { EnemyId.Skeleton , EnemyUIId.Skeleton },
            { EnemyId.SkeletonKnight , EnemyUIId.SkeletonKnight },
            { EnemyId.SkeletonWarrior , EnemyUIId.SkeletonWarrior },
            { EnemyId.SkeletonLordAbyss , EnemyUIId.SkeletonLordAbyss },
            { EnemyId.LivingArmor , EnemyUIId.LivingArmor },
            { EnemyId.SkeletonBrute , EnemyUIId.SkeletonBrute },
            { EnemyId.SkeletonMage0 , EnemyUIId.SkeletonMage },
            { EnemyId.SkeletonSorcerer0 , EnemyUIId.SkeletonSorcerer },
            { EnemyId.DeathKnight , EnemyUIId.DeathKnight },
            { EnemyId.GhostMail , EnemyUIId.GhostMail },
            { EnemyId.AlchemizedSkeleton , EnemyUIId.AlchemizedSkeleton },
            { EnemyId.SkullLord , EnemyUIId.SkullLord },
            { EnemyId.FlameSkeleton , EnemyUIId.FlameSkeleton },
            { EnemyId.FrostSkeleton , EnemyUIId.FrostSkeleton },
            { EnemyId.BoltSkeleton , EnemyUIId.BoltSkeleton },
            { EnemyId.LuxSkeleton , EnemyUIId.LuxSkeleton },
            { EnemyId.DarkSkeleton , EnemyUIId.DarkSkeleton },
            { EnemyId.FlameSkeletonBrute , EnemyUIId.FlameSkeletonBrute },
            { EnemyId.FrostSkeletonBrute , EnemyUIId.FrostSkeletonBrute },
            { EnemyId.BoltSkeletonBrute , EnemyUIId.BoltSkeletonBrute },
            { EnemyId.LuxSkeletonBrute , EnemyUIId.LuxSkeletonBrute },
            { EnemyId.DarkSkeletonBrute , EnemyUIId.DarkSkeletonBrute },
            { EnemyId.Saurian , EnemyUIId.Saurian },
            { EnemyId.GiantSaurian , EnemyUIId.GiantSaurian },
            { EnemyId.SulfurSaurian , EnemyUIId.SulfurSaurian },
            { EnemyId.GiantSulfurSaurian , EnemyUIId.GiantSulfurSaurian },
            { EnemyId.GeoSaurian , EnemyUIId.GeoSaurian },
            { EnemyId.GiantGeoSaurian , EnemyUIId.GiantGeoSaurian },
            { EnemyId.SaurianSage , EnemyUIId.SaurianSage },
            { EnemyId.GiantSaurianSage , EnemyUIId.GiantSaurianSage },
            { EnemyId.PyreSaurianSalamander , EnemyUIId.PyreSaurian },
            { EnemyId.RockSaurian , EnemyUIId.RockSaurian },
            { EnemyId.RockSaurianSpinel , EnemyUIId.RockSaurianSpinel },
            { EnemyId.BlueNewt , EnemyUIId.BlueNewt },
            { EnemyId.LargeNewt , EnemyUIId.LargeNewt },
            { EnemyId.WarReadySaurianLightArmor , EnemyUIId.WarReadySaurian },
            { EnemyId.WarReadyGiantSaurianLightArmor , EnemyUIId.WarReadyGiantSaurian },
            { EnemyId.Merman , EnemyUIId.Merman },
            { EnemyId.PoisonMerman , EnemyUIId.PoisonMerman },
            { EnemyId.UndeadMale , EnemyUIId.Undead },
            { EnemyId.UndeadFemale , EnemyUIId.Undead },
            { EnemyId.StoutUndead , EnemyUIId.StoutUndead },
            { EnemyId.SwordUndead , EnemyUIId.SwordUndead },
            { EnemyId.WarriorUndead , EnemyUIId.WarriorUndead },
            { EnemyId.Eliminator , EnemyUIId.Eliminator },
            { EnemyId.Mudman , EnemyUIId.Mudman },
            { EnemyId.Sludgeman , EnemyUIId.Sludgeman },
            { EnemyId.FrostCorpsePunisher , EnemyUIId.FrostCorpsePunisher },
            { EnemyId.FrostCorpseTorturer , EnemyUIId.FrostCorpseTorturer },
            { EnemyId.FlameCorpsePunisher , EnemyUIId.FlameCorpsePunisher },
            { EnemyId.BoltCorpsePunisher , EnemyUIId.BoltCorpsePunisher },
            { EnemyId.LuxCorpsePunisher , EnemyUIId.LuxCorpsePunisher },
            { EnemyId.DarkCorpsePunisher , EnemyUIId.DarkCorpsePunisher },
            { EnemyId.FlameCorpseTorturer , EnemyUIId.FlameCorpseTorturer },
            { EnemyId.BoltCorpseTorturer , EnemyUIId.BoltCorpseTorturer },
            { EnemyId.LuxCorpseTorturer , EnemyUIId.LuxCorpseTorturer },
            { EnemyId.DarkCorpseTorturer , EnemyUIId.DarkCorpseTorturer },
            { EnemyId.EliminatorSlay , EnemyUIId.EliminatorSlay },
            { EnemyId.Harpy , EnemyUIId.Harpy },
            { EnemyId.SnowHarpy , EnemyUIId.SnowHarpy },
            { EnemyId.Gargoyle , EnemyUIId.Gargoyle },
            { EnemyId.Siren , EnemyUIId.Siren },
            { EnemyId.AlchemizedHarpy , EnemyUIId.AlchemizedHarpy },
            { EnemyId.ShadowHarpy , EnemyUIId.ShadowHarpy },
            { EnemyId.BlazeHarpy , EnemyUIId.BlazeHarpy },
            { EnemyId.Strix , EnemyUIId.Strix },
            { EnemyId.Stymphalides , EnemyUIId.Stymphalídes },
            { EnemyId.InfectedSnowHarpy , EnemyUIId.InfectedSnowHarpy },
            { EnemyId.SeverelyInfectedStymphalides , EnemyUIId.SeverelyInfectedStymphalídes },
            { EnemyId.Ukobach , EnemyUIId.Ukobach },
            { EnemyId.Worm , EnemyUIId.Worm },
            { EnemyId.Leech , EnemyUIId.Leech },
            { EnemyId.ArmoredInsectBlue , EnemyUIId.ArmoredInsect },
            { EnemyId.ArmoredInsectRed , EnemyUIId.ArmoredInsect },
            { EnemyId.ArmoredInsectRedPassiveAi0 , EnemyUIId.ArmoredInsect },
            { EnemyId.ArmoredInsectRedPassiveAi1 , EnemyUIId.ArmoredInsect },
            { EnemyId.Slime , EnemyUIId.Slime },
            { EnemyId.DeepSlime , EnemyUIId.DeepSlime },
            { EnemyId.Ooze , EnemyUIId.Ooze },
            { EnemyId.GluttonOoze , EnemyUIId.GluttonOoze },
            { EnemyId.AquaJelly , EnemyUIId.AquaJelly },
            { EnemyId.PyroSlime , EnemyUIId.PyroSlime },
            { EnemyId.FreezingSlime , EnemyUIId.FreezingSlime },
            { EnemyId.ElectricSlime , EnemyUIId.ElectricSlime },
            { EnemyId.PhotonSlime , EnemyUIId.PhotonSlime },
            { EnemyId.DimSlime , EnemyUIId.DimSlime },
            { EnemyId.Blob , EnemyUIId.Blob },
            { EnemyId.AcidBlob , EnemyUIId.AcidBlob },
            { EnemyId.StoneBlob , EnemyUIId.StoneBlob },
            { EnemyId.OilJelly , EnemyUIId.OilJelly },
            { EnemyId.RogueFighter , EnemyUIId.RogueFighter },
            { EnemyId.RogueSeeker , EnemyUIId.RogueSeeker },
            { EnemyId.RogueHunter , EnemyUIId.RogueHunter },
            { EnemyId.RogueHealer , EnemyUIId.RogueHealer },
            { EnemyId.RogueDefender , EnemyUIId.RogueDefender },
            { EnemyId.RogueMage , EnemyUIId.RogueMage },
            { EnemyId.RogueWarrior , EnemyUIId.RogueWarrior },
            { EnemyId.BandedFighter , EnemyUIId.BandedFighter },
            { EnemyId.BandedSeeker , EnemyUIId.BandedSeeker },
            { EnemyId.BandedHunter , EnemyUIId.BandedHunter },
            { EnemyId.BandedHealer , EnemyUIId.BandedHealer },
            { EnemyId.BandedDefender , EnemyUIId.BandedDefender },
            { EnemyId.BandedMage , EnemyUIId.BandedMage },
            { EnemyId.BandedWarrior , EnemyUIId.BandedWarrior },
            { EnemyId.MerganFighter , EnemyUIId.MerganFighter },
            { EnemyId.MerganSeeker , EnemyUIId.MerganSeeker },
            { EnemyId.MerganHunter , EnemyUIId.MerganHunter },
            { EnemyId.MerganHealer , EnemyUIId.MerganHealer },
            { EnemyId.MerganDefender , EnemyUIId.MerganDefender },
            { EnemyId.MerganMage , EnemyUIId.MerganMage },
            { EnemyId.MerganWarrior , EnemyUIId.MerganWarrior },
            { EnemyId.MerganElementArcher , EnemyUIId.MerganElementArcher },
            { EnemyId.MistFighter , EnemyUIId.MistFighter },
            { EnemyId.MistHunter , EnemyUIId.MistHunter },
            { EnemyId.MistPriest , EnemyUIId.MistPriest },
            { EnemyId.MistSorcerer , EnemyUIId.MistSorcerer },
            { EnemyId.MistWarrior , EnemyUIId.MistWarrior },
            { EnemyId.Iris , EnemyUIId.Iris },
            { EnemyId.DiamantesHuman , EnemyUIId.Diamantes },
            { EnemyId.Leo , EnemyUIId.Leo },
            { EnemyId.HoodedIris , EnemyUIId.HoodedIris },
            { EnemyId.FormerCommanderLeoFinalBoss , EnemyUIId.FormerArisenCorpsLeaderLeo },
            { EnemyId.PawnFighter , EnemyUIId.PawnFighter },
            { EnemyId.PawnSeeker , EnemyUIId.PawnSeeker },
            { EnemyId.PawnHunter , EnemyUIId.PawnHunter },
            { EnemyId.PawnHealer , EnemyUIId.PawnHealer },
            { EnemyId.PawnDefender , EnemyUIId.PawnDefender },
            { EnemyId.PawnMage , EnemyUIId.PawnMage },
            { EnemyId.PawnWarrior , EnemyUIId.PawnWarrior },
            { EnemyId.PawnElementArcher , EnemyUIId.PawnElementArcher },
            { EnemyId.PhindymianFighter , EnemyUIId.PhindymianFighter },
            { EnemyId.PhindymianSeeker , EnemyUIId.PhindymianSeeker },
            { EnemyId.PhindymianHunter , EnemyUIId.PhindymianHunter },
            { EnemyId.PhindymianPriest , EnemyUIId.PhindymianPriest },
            { EnemyId.PhindymianDefender , EnemyUIId.PhindymianDefender },
            { EnemyId.PhindymianSorcerer , EnemyUIId.PhindymianSorcerer },
            { EnemyId.PhindymianWarrior , EnemyUIId.PhindymianWarrior },
            { EnemyId.PhindymianElementArcher , EnemyUIId.PhindymianElementArcher },
            { EnemyId.ScarletFighter , EnemyUIId.ScarletFighter },
            { EnemyId.ScarletSeeker , EnemyUIId.ScarletSeeker },
            { EnemyId.ScarletHunter , EnemyUIId.ScarletHunter },
            { EnemyId.ScarletHealer , EnemyUIId.ScarletHealer },
            { EnemyId.ScarletDefender , EnemyUIId.ScarletDefender },
            { EnemyId.ScarletMage , EnemyUIId.ScarletMage },
            { EnemyId.ScarletWarrior , EnemyUIId.ScarletWarrior },
            { EnemyId.MegadoGuardFighter , EnemyUIId.MegadoGuard },
            { EnemyId.MegadoGuardSeeker , EnemyUIId.MegadoGuard },
            { EnemyId.MegadoGuardHunter , EnemyUIId.MegadoGuard },
            { EnemyId.MegadoGuardWarrior , EnemyUIId.MegadoGuard },
            { EnemyId.ForestGoblin , EnemyUIId.ForestGoblin },
            { EnemyId.ForestGoblinFighter , EnemyUIId.ForestGoblinFighter },
            { EnemyId.SlingForestGoblin , EnemyUIId.SlingForestGoblin },
            { EnemyId.Redcap , EnemyUIId.Redcap },
            { EnemyId.RedcapFighter , EnemyUIId.RedcapFighter },
            { EnemyId.SlingRedcap , EnemyUIId.SlingRedcap },
            { EnemyId.AlchemizedGoblin , EnemyUIId.AlchemizedGoblin },
            { EnemyId.AlchemizedGoblinFighter , EnemyUIId.AlchemizedGoblinFighter },
            { EnemyId.AlchemizedSlingGoblin , EnemyUIId.AlchemizedSlingGoblin },
            { EnemyId.DamnedGoblin , EnemyUIId.DamnedGoblin },
            { EnemyId.DamnedSlingGoblinFlask , EnemyUIId.DamnedSlingGoblin },
            { EnemyId.DamnedGoblinFighter , EnemyUIId.DamnedGoblinFighter },
            { EnemyId.ShadowGoblin , EnemyUIId.ShadowGoblin },
            { EnemyId.ShadowGoblinFighter , EnemyUIId.ShadowGoblinFighter },
            { EnemyId.ShadowSlingGoblin , EnemyUIId.ShadowSlingGoblin },
            { EnemyId.GoblinKingNpc , EnemyUIId.GoblinKing },
            { EnemyId.GoblinBomber , EnemyUIId.GoblinBomber },
            { EnemyId.ShadowGoblinLeader , EnemyUIId.ShadowGoblinLeader },
            { EnemyId.BlazeGoblin , EnemyUIId.BlazeGoblin },
            { EnemyId.BlazeGoblinFighter , EnemyUIId.BlazeGoblin },
            { EnemyId.BlazeGoblinSling , EnemyUIId.BlazeGoblin },
            { EnemyId.BlazeGoblinLeader , EnemyUIId.BlazeGoblinLeader },
            { EnemyId.KillerBee , EnemyUIId.KillerBee },
            { EnemyId.AlbeParasiticPoison , EnemyUIId.Albe },
            { EnemyId.MothCyanSleep , EnemyUIId.Moth },
            { EnemyId.MothMagentaPoison , EnemyUIId.Moth },
            { EnemyId.Mandragora , EnemyUIId.Mandragora },
            { EnemyId.MandragoraFlower , EnemyUIId.Mandragora },
            { EnemyId.Habanero , EnemyUIId.Habanero },
            { EnemyId.Maneater , EnemyUIId.Maneater },
            { EnemyId.ManeaterClosed , EnemyUIId.Maneater },
            { EnemyId.TentacleEvilEye0 , EnemyUIId.Tentacle0 },
            { EnemyId.TentacleEvilEye1 , EnemyUIId.Tentacle0 },
            { EnemyId.TentacleVoltEye0 , EnemyUIId.Tentacle0 },
            { EnemyId.TentacleVoltEye1 , EnemyUIId.Tentacle0 },
            { EnemyId.FootBiter , EnemyUIId.FootBiter },
            { EnemyId.Cyclops0 , EnemyUIId.Cyclops },
            { EnemyId.CyclopsClub , EnemyUIId.Cyclops },
            { EnemyId.ArmoredCyclops , EnemyUIId.ArmoredCyclops },
            { EnemyId.ArmoredCyclopsClub , EnemyUIId.ArmoredCyclops },
            { EnemyId.CyclopsGiant , EnemyUIId.Cyclops },
            { EnemyId.Gorecyclops0 , EnemyUIId.Gorecyclops },
            { EnemyId.InfectedGorecyclops , EnemyUIId.InfectedGorecyclops },
            { EnemyId.SeverelyInfectedGorecyclops , EnemyUIId.SeverelyInfectedGorecyclops },
            { EnemyId.Colossus0 , EnemyUIId.Colossus },
            { EnemyId.GrandEnt0 , EnemyUIId.GrandEnt },
            { EnemyId.Ent , EnemyUIId.Ent },
            { EnemyId.PhindymianEnt0 , EnemyUIId.PhindymianEnt },
            { EnemyId.BurnedEnt , EnemyUIId.BurnedEnt },
            { EnemyId.Troll , EnemyUIId.Troll },
            { EnemyId.MoleTroll0 , EnemyUIId.MoleTroll },
            { EnemyId.Fodden , EnemyUIId.Fodden },
            { EnemyId.SkeletonCyclops , EnemyUIId.SkeletonCyclops },
            { EnemyId.SkeletonCyclopsTest , EnemyUIId.SkeletonCyclops },
            { EnemyId.FrostSkeletonCyclops , EnemyUIId.FrostSkeletonCyclops },
            { EnemyId.BoltSkeletonCyclops , EnemyUIId.BoltSkeletonCyclops },
            { EnemyId.FlameSkeletonCyclops , EnemyUIId.FlameSkeletonCyclops },
            { EnemyId.WarReadyGorecyclopsLightArmor0 , EnemyUIId.WarReadyGorecyclops },
            { EnemyId.WarReadyGorecyclopsLightArmor1 , EnemyUIId.WarReadyGorecyclops },
            { EnemyId.Golem , EnemyUIId.Golem },
            { EnemyId.Goliath , EnemyUIId.Goliath },
            { EnemyId.DamnedGolem , EnemyUIId.DamnedGolem },
            { EnemyId.GeoGolem , EnemyUIId.GeoGolem },
            { EnemyId.GoliathCyclopsTest , EnemyUIId.Goliath },
            { EnemyId.Chimera0 , EnemyUIId.Chimera },
            { EnemyId.Gorechimera0 , EnemyUIId.Gorechimera },
            { EnemyId.WhiteChimera0 , EnemyUIId.WhiteChimera },
            { EnemyId.ShadowChimera , EnemyUIId.ShadowChimera },
            { EnemyId.BlazeChimera , EnemyUIId.BlazeChimera },
            { EnemyId.Manticore0 , EnemyUIId.Manticore },
            { EnemyId.Goremanticore , EnemyUIId.Goremanticore },
            { EnemyId.WarReadyGoremanticoreLightArmor , EnemyUIId.WarReadyGoremanticore },
            { EnemyId.Abaddon0 , EnemyUIId.Abaddon },
            { EnemyId.Griffin0 , EnemyUIId.Griffin },
            { EnemyId.Cockatrice , EnemyUIId.Cockatrice },
            { EnemyId.Sphinx0 , EnemyUIId.Sphinx },
            { EnemyId.BlackGriffin0 , EnemyUIId.BlackGriffin },
            { EnemyId.AlchemizedGriffin , EnemyUIId.AlchemizedGriffin },
            { EnemyId.Nightmare , EnemyUIId.Nightmare },
            { EnemyId.InfectedGriffin , EnemyUIId.InfectedGriffin },
            { EnemyId.SeverelyInfectedGriffin , EnemyUIId.SeverelyInfectedGriffin },
            { EnemyId.WhiteGriffin0 , EnemyUIId.WhiteGriffin },
            { EnemyId.Bifrest0 , EnemyUIId.Bifrest },
            { EnemyId.WarReadyNightmareLightArmor , EnemyUIId.WarReadyNightmare },
            { EnemyId.EvilEye0 , EnemyUIId.EvilEye },
            { EnemyId.VileEye , EnemyUIId.VileEye },
            { EnemyId.VoltEye , EnemyUIId.VoltEye },
            { EnemyId.CrystalEye , EnemyUIId.CrystalEye },
            { EnemyId.RubyEye , EnemyUIId.RubyEye },
            { EnemyId.LapisEye , EnemyUIId.LapisEye },
            { EnemyId.EmeraldEye , EnemyUIId.EmeraldEye },
            { EnemyId.AlchemyEye , EnemyUIId.AlchemyEye },
            { EnemyId.Ogre , EnemyUIId.Ogre },
            { EnemyId.DreadApe , EnemyUIId.DreadApe },
            { EnemyId.Ghoul0 , EnemyUIId.Ghoul },
            { EnemyId.BruteApe , EnemyUIId.BruteApe },
            { EnemyId.SilverRoar , EnemyUIId.SilverRoar },
            { EnemyId.Spineback0 , EnemyUIId.Spineback },
            { EnemyId.LittleSpine , EnemyUIId.LittleSpine },
            { EnemyId.Cragger , EnemyUIId.Cragger },
            { EnemyId.LittleCrag , EnemyUIId.LittleCrag },
            { EnemyId.WarReadyOgreLightArmor , EnemyUIId.WarReadyOgre },
            { EnemyId.Wight0 , EnemyUIId.Wight },
            { EnemyId.Death , EnemyUIId.Death },
            { EnemyId.Witch , EnemyUIId.Witch },
            { EnemyId.EmpressGhost , EnemyUIId.EmpressGhost },
            { EnemyId.Medusa , EnemyUIId.Medusa },
            { EnemyId.Gorgon , EnemyUIId.Gorgon },
            { EnemyId.Ghost , EnemyUIId.Ghost },
            { EnemyId.MiseryGhost , EnemyUIId.MiseryGhost },
            { EnemyId.GrudgeGhost , EnemyUIId.GrudgeGhost },
            { EnemyId.RageGhost , EnemyUIId.RageGhost },
            { EnemyId.Drake0 , EnemyUIId.Drake },
            { EnemyId.Wyrm0 , EnemyUIId.Wyrm },
            { EnemyId.CursedDragon , EnemyUIId.CursedDragon },
            { EnemyId.Lindwurm0 , EnemyUIId.Lindwurm },
            { EnemyId.Angules0 , EnemyUIId.Angules },
            { EnemyId.Behemoth0 , EnemyUIId.Behemoth },
            { EnemyId.MistDrake , EnemyUIId.MistDrake },
            { EnemyId.MistWyrm , EnemyUIId.MistWyrm },
            { EnemyId.InfectedBehemoth , EnemyUIId.InfectedBehemoth },
            { EnemyId.SeverelyInfectedBehemoth , EnemyUIId.SeverelyInfectedBehemoth },
            { EnemyId.LotusFin , EnemyUIId.LotusFin },
            { EnemyId.Dagon , EnemyUIId.Dagon },
            { EnemyId.Tarasque , EnemyUIId.Tarasque },
            { EnemyId.WisenedTarasque0 , EnemyUIId.WisenedTarasque },
            { EnemyId.WhiteTarasque , EnemyUIId.WhiteTarasque },
            { EnemyId.Catoblepas , EnemyUIId.Catoblepas },
            { EnemyId.OrcSoldier0 , EnemyUIId.OrcSoldier },
            { EnemyId.OrcAimer , EnemyUIId.OrcAimer },
            { EnemyId.OrcBanger , EnemyUIId.OrcBanger },
            { EnemyId.OrcBattler , EnemyUIId.OrcBattler },
            { EnemyId.OrcBringer , EnemyUIId.OrcBringer },
            { EnemyId.OrcTrooper  , EnemyUIId.OrcTrooper },
            { EnemyId.InfectedOrcSoldier , EnemyUIId.InfectedOrcSoldier },
            { EnemyId.InfectedOrcAimer , EnemyUIId.InfectedOrcAimer },
            { EnemyId.InfectedOrcBanger , EnemyUIId.InfectedOrcBanger },
            { EnemyId.CaptainOrc0 , EnemyUIId.CaptainOrc },
            { EnemyId.SwordSoldierDwarfOrc , EnemyUIId.SwordSoldierDwarfOrc },
            { EnemyId.BluntSoldierDwarfOrc , EnemyUIId.BluntSoldierDwarfOrc },
            { EnemyId.HeavySoldierDwarfOrc , EnemyUIId.HeavySoldierDwarfOrc },
            { EnemyId.RangedSoldierDwarfOrc , EnemyUIId.RangedSoldierDwarfOrc },
            { EnemyId.DwarfOrcTest , EnemyUIId.DwarfOrc },
            { EnemyId.SquadLeaderDwarfOrc , EnemyUIId.SquadLeaderDwarfOrc },
            { EnemyId.GeneralOrc , EnemyUIId.GeneralOrc },
            { EnemyId.AncestorOrc , EnemyUIId.AncestorOrc },
            { EnemyId.AncestorOrcFighter , EnemyUIId.AncestorOrc },
            { EnemyId.AncestorOrcDifferentBones , EnemyUIId.AncestorOrc },
            { EnemyId.Legion , EnemyUIId.Legion },
            { EnemyId.LegionFighter , EnemyUIId.Legion },
            { EnemyId.LegionDifferentBones , EnemyUIId.Legion },
            { EnemyId.LegionLeader , EnemyUIId.LegionLeader },
            { EnemyId.CaptainAncestorOrc , EnemyUIId.CaptainAncestorOrc },
            { EnemyId.Mogok , EnemyUIId.Mogok },
            { EnemyId.GigantMachina , EnemyUIId.GigantMachina },
            { EnemyId.FrostMachina , EnemyUIId.FrostMachina },
            { EnemyId.BoltMachina , EnemyUIId.BoltMachina },
            { EnemyId.WarMaster0 , EnemyUIId.WarMaster },
            { EnemyId.BeastMaster0 , EnemyUIId.BeastCommander },
            { EnemyId.NecroMaster , EnemyUIId.NecroMaster },
            { EnemyId.ShadowMasterInvulnerable , EnemyUIId.ShadowMaster },
            { EnemyId.AncestorOrigin , EnemyUIId.AncestorOrigin },
            { EnemyId.Grigori , EnemyUIId.Grigori },
            { EnemyId.SeverelyInfectedDemon , EnemyUIId.SeverelyInfectedDemon },
            { EnemyId.BeardedGrigori , EnemyUIId.BeardedGrigori },
            { EnemyId.Samyaza , EnemyUIId.Samyaza },
            { EnemyId.BlazeGrigori , EnemyUIId.BlazeGrigori },
            { EnemyId.ShadowGrigori , EnemyUIId.ShadowGrigori },
            { EnemyId.Rabbit , EnemyUIId.Rabbit },
            { EnemyId.Buck , EnemyUIId.Buck },
            { EnemyId.Doe , EnemyUIId.Doe },
            { EnemyId.Ox , EnemyUIId.Ox },
            { EnemyId.GiantRat , EnemyUIId.GiantRat },
            { EnemyId.Boar , EnemyUIId.Boar },
            { EnemyId.Pig , EnemyUIId.Pig },
            { EnemyId.Piglet , EnemyUIId.Piglet },
            { EnemyId.PigDirty , EnemyUIId.Pig },
            { EnemyId.PigletDirty , EnemyUIId.Piglet },
            { EnemyId.Spider , EnemyUIId.Spider },
            { EnemyId.ChickenWhite , EnemyUIId.Chicken },
            { EnemyId.ChickenBrown , EnemyUIId.Chicken },
            { EnemyId.Goat , EnemyUIId.Goat },
            { EnemyId.FrogGold , EnemyUIId.Frog },
            { EnemyId.FrogBlue , EnemyUIId.Frog },
            { EnemyId.WildBoarBrown , EnemyUIId.WildBoar },
            { EnemyId.WildBoarStripes , EnemyUIId.WildBoar },
            { EnemyId.Zuhl0 , EnemyUIId.Zuhl },
            { EnemyId.AlteredZuhl , EnemyUIId.AlteredZuhl },
            { EnemyId.RedZuhl , EnemyUIId.RedZuhl },
            { EnemyId.Diamantes , EnemyUIId.Diamantes },
            { EnemyId.Scourge0 , EnemyUIId.Scourge },
            { EnemyId.Baphomet0 , EnemyUIId.Baphomet },
            { EnemyId.SeverelyInfectedScourge , EnemyUIId.SeverelyInfectedScourge },
            { EnemyId.BlackKnightDarkOnly , EnemyUIId.BlackKnight },
            { EnemyId.BlackKnightHolyIce0 , EnemyUIId.BlackKnight },
            { EnemyId.BlackKnightHolyIce1 , EnemyUIId.BlackKnight },
            { EnemyId.Ifrit1stForm , EnemyUIId.Ifrit },
            { EnemyId.Ifrit2ndForm , EnemyUIId.Ifrit },
            { EnemyId.WhiteDragonNpc , EnemyUIId.TheWhiteDragon },
            { EnemyId.ElderDragon0 , EnemyUIId.ElderDragon },
            { EnemyId.Golgorran0 , EnemyUIId.Golgorran0 },
            { EnemyId.WhiteDragon , EnemyUIId.PhantasmicGreatDragon },
            { EnemyId.Ushumgal , EnemyUIId.Ushumgal },
            { EnemyId.SpiritDragonWillmia0 , EnemyUIId.SpiritDragonWillmia },
            { EnemyId.SpiritDragonWillmiaGoblinTest , EnemyUIId.SpiritDragonWillmia },
            { EnemyId.TheEvilDragon0 , EnemyUIId.TheEvilDragon0 },
            { EnemyId.BlackDragon1stForm0 , EnemyUIId.BlackDragon },
            { EnemyId.BlackDragon2ndFormUntranslated , EnemyUIId.PowerthatDestroysReason },
            { EnemyId.BlackDragon2ndFormDamaged , EnemyUIId.PowerthatDestroysReason },
            { EnemyId.UnspeakableMeat , EnemyUIId.UnspeakableMeat },
            { EnemyId.GiantUnspeakableMeat , EnemyUIId.GiantUnspeakableMeat },
            { EnemyId.DragonCrystalOfPrayingSpiritDragonWillmiaWm , EnemyUIId.DragonCrystalofPraying },
            { EnemyId.DragonCrystalOfGroaningSpiritDragonWillmiaWm , EnemyUIId.DragonCrystalofGroaning },
            { EnemyId.NoEnemyInCombat0 , EnemyUIId.Invisibleaggroenemy },
            { EnemyId.DragonCrystalTheEvilDragonWmUntranslated , EnemyUIId.EvilDragonTest },
            { EnemyId.NoEnemyInCombat1 , EnemyUIId.Invisibleaggroenemy },
            { EnemyId.TotemShadowMasterWmUntranslated , EnemyUIId.Grudge },
            { EnemyId.NoEnemyInCombat2 , EnemyUIId.Invisibleaggroenemy },
            { EnemyId.DragonCrystalOfDarknessInvulnerableGround , EnemyUIId.DragonCrystalofDarkness },
            { EnemyId.DragonCrystalOfDarknessInvulnerableFlying , EnemyUIId.DragonCrystalofDarkness },
            { EnemyId.CrystalOfBlessing , EnemyUIId.CrystalofBlessing },
            { EnemyId.DragonCrystalOfDarknessFlyingUntranslated , EnemyUIId.DragonCrystalofDarkness },
            { EnemyId.DragonCrystalOfDestruction , EnemyUIId.DragonCrystalofDestruction },
            { EnemyId.DragonCrystalOfBindingBlackDragon , EnemyUIId.DragonCrystalofBinding },
            { EnemyId.BlackSword0 , EnemyUIId.BlackSword },
            { EnemyId.Colossus1 , EnemyUIId.Colossus },
            { EnemyId.Colossus2 , EnemyUIId.Colossus },
            { EnemyId.Gorecyclops1 , EnemyUIId.Gorecyclops },
            { EnemyId.Gorecyclops2 , EnemyUIId.Gorecyclops },
            { EnemyId.Ghoul1 , EnemyUIId.Ghoul },
            { EnemyId.Spineback1 , EnemyUIId.Spineback },
            { EnemyId.Spineback2 , EnemyUIId.Spineback },
            { EnemyId.MoleTroll1 , EnemyUIId.MoleTroll },
            { EnemyId.GrandEnt1 , EnemyUIId.GrandEnt },
            { EnemyId.PhindymianEnt1 , EnemyUIId.PhindymianEnt },
            { EnemyId.Griffin1 , EnemyUIId.Griffin },
            { EnemyId.BlackGriffin1 , EnemyUIId.BlackGriffin },
            { EnemyId.WhiteGriffin1 , EnemyUIId.WhiteGriffin },
            { EnemyId.Bifrest1 , EnemyUIId.Bifrest },
            { EnemyId.Bifrest2 , EnemyUIId.Bifrest },
            { EnemyId.Sphinx1 , EnemyUIId.Sphinx },
            { EnemyId.Chimera1 , EnemyUIId.Chimera },
            { EnemyId.WhiteChimera1 , EnemyUIId.WhiteChimera },
            { EnemyId.Gorechimera1 , EnemyUIId.Gorechimera },
            { EnemyId.Manticore1 , EnemyUIId.Manticore },
            { EnemyId.Drake1 , EnemyUIId.Drake },
            { EnemyId.Wyrm1 , EnemyUIId.Wyrm },
            { EnemyId.Angules1 , EnemyUIId.Angules },
            { EnemyId.Behemoth1 , EnemyUIId.Behemoth },
            { EnemyId.Lindwurm1 , EnemyUIId.Lindwurm },
            { EnemyId.TarasqueGoblinTest , EnemyUIId.Tarasque },
            { EnemyId.ElderDragonEpitathRoadTrial , EnemyUIId.ElderDragon },
            { EnemyId.BlackDragon1stFormCutscene , EnemyUIId.BlackDragon },
            { EnemyId.BlackDragon2ndFormCutscene , EnemyUIId.BlackDragon },
            { EnemyId.ShadowMasterGiant , EnemyUIId.ShadowMaster },
            { EnemyId.WarMaster1 , EnemyUIId.WarMaster },
            { EnemyId.BeastMaster1 , EnemyUIId.BeastCommander },
            { EnemyId.Zuhl1 , EnemyUIId.Zuhl },
            { EnemyId.Scourge1 , EnemyUIId.Scourge },
            { EnemyId.BaphometEnraged , EnemyUIId.Baphomet },
            { EnemyId.SkeletonMage1 , EnemyUIId.SkeletonMage },
            { EnemyId.SkeletonMageDifferentAi , EnemyUIId.SkeletonMage },
            { EnemyId.SkeletonSorcerer1 , EnemyUIId.SkeletonSorcerer },
            { EnemyId.SkeletonSorcerer2 , EnemyUIId.SkeletonSorcerer },
            { EnemyId.SkeletonSorcerer3 , EnemyUIId.SkeletonSorcerer },
            { EnemyId.TheEvilDragonSparks , EnemyUIId.TheEvilDragon1 },
            { EnemyId.TheEvilDragon1 , EnemyUIId.TheEvilDragon1 },
            { EnemyId.Wight1 , EnemyUIId.Wight },
            { EnemyId.AlbeSNest , EnemyUIId.InsectMound },
            { EnemyId.ElderDragon1 , EnemyUIId.ElderDragon },
            { EnemyId.Golgorran1 , EnemyUIId.Golgorran1 },
            { EnemyId.GrandEnt2 , EnemyUIId.GrandEnt },
            { EnemyId.Zuhl2 , EnemyUIId.Zuhl },
            { EnemyId.SpiritDragonWillmia1 , EnemyUIId.SpiritDragonWillmia },
            { EnemyId.BlackKnightPhantomClear , EnemyUIId.BlackKnightPhantom },
            { EnemyId.BlackKnight , EnemyUIId.BlackKnight },
            { EnemyId.BlackKnightFanOfSwords , EnemyUIId.BlackKnight },
            { EnemyId.BlackKnightPhantomOpaque , EnemyUIId.BlackKnightPhantom },
            { EnemyId.ArisenOfTheBlackDragon , EnemyUIId.ArisenoftheBlackDragon },
            { EnemyId.BlackSword1 , EnemyUIId.BlackSword },
            { EnemyId.WisenedTarasque1 , EnemyUIId.WisenedTarasque },
            { EnemyId.EvilEye1 , EnemyUIId.EvilEye },
            { EnemyId.Abbadon1 , EnemyUIId.Abaddon },
            { EnemyId.Albe , EnemyUIId.Albe },
            { EnemyId.Baphomet1 , EnemyUIId.Baphomet },
            { EnemyId.BaphometGlowingPurple , EnemyUIId.Baphomet },
            { EnemyId.BlackDragon1stForm1 , EnemyUIId.BlackDragon },
            { EnemyId.BlackDragon2ndForm , EnemyUIId.PowerthatDestroysReason },
            { EnemyId.BlackDragon1stFormAgainEm , EnemyUIId.BlackDragon },
            { EnemyId.BlackDragon2ndFormAgainEm , EnemyUIId.PowerthatDestroysReason },
            { EnemyId.DragonCrystalOfDestructionShootsLaserRocks , EnemyUIId.DragonCrystalofDestruction },
            { EnemyId.DragonCrystalOfDestructionSucksYouInWithMagic0 , EnemyUIId.DragonCrystalofDestruction },
            { EnemyId.DragonCrystalOfDestructionLotsOfLaserRocksAndBigExplosion , EnemyUIId.DragonCrystalofDestruction },
            { EnemyId.DragonCrystalOfDestructionSucksYouInWithMagic1 , EnemyUIId.DragonCrystalofDestruction },
            { EnemyId.OrcSoldier1 , EnemyUIId.OrcSoldier },
            { EnemyId.OrcSoldier2 , EnemyUIId.OrcSoldier },
            { EnemyId.OrcSoldier3 , EnemyUIId.OrcSoldier },
            { EnemyId.OrcSoldier4 , EnemyUIId.OrcSoldier },
            { EnemyId.CaptainOrc1 , EnemyUIId.CaptainOrc },
            { EnemyId.OrcGoblinTest , EnemyUIId.GoblinOrc },
            { EnemyId.GoblinFighter1 , EnemyUIId.GoblinFighter },
            { EnemyId.GoblinFighter2 , EnemyUIId.GoblinFighter },
            { EnemyId.GoblinFighter3 , EnemyUIId.GoblinFighter },
            { EnemyId.GoblinFighter4 , EnemyUIId.GoblinFighter },
            { EnemyId.GoblinFighter5 , EnemyUIId.GoblinFighter },
            { EnemyId.GoblinFighter6 , EnemyUIId.GoblinFighter },
            { EnemyId.GoblinFighter7 , EnemyUIId.GoblinFighter },
            { EnemyId.GoblinFighter8 , EnemyUIId.GoblinFighter },
            { EnemyId.GoblinFighter9 , EnemyUIId.GoblinFighter },
            { EnemyId.GoblinFighter10 , EnemyUIId.GoblinFighter },
            { EnemyId.Cyclops1 , EnemyUIId.Cyclops },
            { EnemyId.Cyclops2 , EnemyUIId.Cyclops },
            { EnemyId.Cyclops3 , EnemyUIId.Cyclops },
            { EnemyId.Cyclops4 , EnemyUIId.Cyclops },
            { EnemyId.Cyclops5 , EnemyUIId.Cyclops },
            { EnemyId.GigantMachinaTrinity , EnemyUIId.GigantMachinaTrinity },
            { EnemyId.FrostMachinaTrinity , EnemyUIId.FrostMachinaTrinity },
            { EnemyId.BoltMachinaTrinity , EnemyUIId.BoltMachinaTrinity },
            { EnemyId.BehemothTest , EnemyUIId.Behemoth },
            { EnemyId.BlackKnightGettingInjuredCutscene , EnemyUIId.BlackKnight },
            { EnemyId.SpiritDragonWillmiaTest , EnemyUIId.SpiritDragonWillmia },
            { EnemyId.SpiritDragonWillmiaActive , EnemyUIId.SpiritDragonWillmia },
        };

        public static HmPresetId GetHmPresetId(this EnemyId enemyId)
        {
            if (HmPresetMap.ContainsKey(enemyId))
            {
                return HmPresetMap[enemyId];
            }
            return HmPresetId.None;
        }

        public static EnemyUIId GetUIId(this EnemyId enemyId)
        {
            return NameMap.GetValueOrDefault(enemyId, EnemyUIId.None);
        }
    }
}
