using System.Collections.Generic;

namespace Arrowgene.Ddon.Shared.Model
{
    //Source reference: http://ddon.wikidot.com/creatures:home
    //Secondary source: H1G
    public enum Species
    {
        Unknown,
        Alchemized,
        Beast,
        Construct,
        Cursed,
        DemiHuman,
        Demon,
        Demonkin,
        Dragonkin,
        Formless,
        Giant,
        Human,
        Infected,
        Spirit,
        Skeletal,
        Undead,
        Winged,
        WarReady
    }

    public static class EnemySpeciesId
    {
        public static Species GetSpecies(this EnemyId enemyId)
        { 
            if (!EnemySpeciesMap.ContainsKey(enemyId))
            { 
                return Species.Unknown;
            }

            return EnemySpeciesMap[enemyId];
        }

        public static bool IsSpecies(this EnemyId enemyId, Species species)
        {
            return enemyId.GetSpecies() == species;
        }

        public static List<EnemyId> GetEnemies(this Species species)
        {
            List<EnemyId> list = new List<EnemyId>();

            foreach(var kvp in EnemySpeciesMap)
            {
                if (kvp.Value == species)
                {
                    list.Add(kvp.Key);
                }
            }

            return list;
        }

        private static readonly Dictionary<EnemyId, Species> EnemySpeciesMap = new Dictionary<EnemyId, Species>()
        {
            [EnemyId.Abaddon0] = Species.Beast, //Manticore but not a Demon apparently?
            [EnemyId.Abbadon1] = Species.Beast,
            [EnemyId.AcidBlob] = Species.Formless,
            [EnemyId.Albe] = Species.Winged,
            [EnemyId.AlbeParasiticPoison] = Species.Winged,
            [EnemyId.AlbeSNest] = Species.Unknown,
            [EnemyId.AlchemizedGoblin] = Species.Alchemized,
            [EnemyId.AlchemizedGoblinFighter] = Species.Alchemized,
            [EnemyId.AlchemizedGriffin] = Species.Alchemized,
            [EnemyId.AlchemizedHarpy] = Species.Alchemized,
            [EnemyId.AlchemizedSkeleton] = Species.Alchemized,
            [EnemyId.AlchemizedSlingGoblin] = Species.Alchemized,
            [EnemyId.AlchemizedWolf] = Species.Alchemized,
            [EnemyId.AlchemyEye] = Species.Alchemized,
            [EnemyId.AlteredZuhl] = Species.Demon,
            [EnemyId.AncestorOrc] = Species.Demonkin,
            [EnemyId.AncestorOrcDifferentBones] = Species.Demonkin,
            [EnemyId.AncestorOrcFighter] = Species.Demonkin,
            [EnemyId.AncestorOrigin] = Species.Demonkin,
            [EnemyId.Angules0] = Species.Dragonkin,
            [EnemyId.Angules1] = Species.Dragonkin,
            [EnemyId.AquaJelly] = Species.Formless,
            [EnemyId.ArisenOfTheBlackDragon] = Species.Spirit,
            [EnemyId.ArmoredCyclops] = Species.Giant,
            [EnemyId.ArmoredCyclopsClub] = Species.Giant,
            [EnemyId.ArmoredInsectBlue] = Species.Beast,
            [EnemyId.ArmoredInsectRed] = Species.Beast,
            [EnemyId.ArmoredInsectRedPassiveAi0] = Species.Beast,
            [EnemyId.ArmoredInsectRedPassiveAi1] = Species.Beast,
            [EnemyId.BandedDefender] = Species.Human,
            [EnemyId.BandedFighter] = Species.Human,
            [EnemyId.BandedHealer] = Species.Human,
            [EnemyId.BandedHunter] = Species.Human,
            [EnemyId.BandedMage] = Species.Human,
            [EnemyId.BandedSeeker] = Species.Human,
            [EnemyId.BandedWarrior] = Species.Human,
            [EnemyId.Baphomet0] = Species.Demon,
            [EnemyId.Baphomet1] = Species.Demon,
            [EnemyId.BaphometEnraged] = Species.Demon,
            [EnemyId.BaphometGlowingPurple] = Species.Demon,
            [EnemyId.Bat] = Species.Winged,
            [EnemyId.BeardedGrigori] = Species.Demon,
            [EnemyId.BeastMaster0] = Species.Demonkin,
            [EnemyId.BeastMaster1] = Species.Demonkin,
            [EnemyId.Behemoth0] = Species.Dragonkin,
            [EnemyId.Behemoth1] = Species.Dragonkin,
            [EnemyId.BehemothGoblinTest] = Species.Dragonkin,
            [EnemyId.BehemothTest] = Species.Dragonkin,
            [EnemyId.Bifrest0] = Species.Winged,
            [EnemyId.Bifrest1] = Species.Winged,
            [EnemyId.Bifrest2] = Species.Winged,
            [EnemyId.BlackDragon1stForm0] = Species.Dragonkin,
            [EnemyId.BlackDragon1stForm1] = Species.Dragonkin,
            [EnemyId.BlackDragon1stFormAgainEm] = Species.Dragonkin,
            [EnemyId.BlackDragon1stFormCutscene] = Species.Dragonkin,
            [EnemyId.BlackDragon2ndForm] = Species.Dragonkin,
            [EnemyId.BlackDragon2ndFormAgainEm] = Species.Dragonkin,
            [EnemyId.BlackDragon2ndFormCutscene] = Species.Dragonkin,
            [EnemyId.BlackDragon2ndFormDamaged] = Species.Dragonkin,
            [EnemyId.BlackDragon2ndFormUntranslated] = Species.Dragonkin,
            [EnemyId.BlackGriffin0] = Species.Winged,
            [EnemyId.BlackGriffin1] = Species.Winged,
            [EnemyId.BlackKnight] = Species.Spirit,
            [EnemyId.BlackKnightDarkOnly] = Species.Spirit,
            [EnemyId.BlackKnightFanOfSwords] = Species.Spirit,
            [EnemyId.BlackKnightGettingInjuredCutscene] = Species.Spirit,
            [EnemyId.BlackKnightHolyIce0] = Species.Spirit,
            [EnemyId.BlackKnightHolyIce1] = Species.Spirit,
            [EnemyId.BlackKnightPhantomClear] = Species.Spirit,
            [EnemyId.BlackKnightPhantomOpaque] = Species.Spirit,
            [EnemyId.BlackSword0] = Species.Unknown,
            [EnemyId.BlackSword1] = Species.Unknown,
            [EnemyId.BlazeChimera] = Species.Spirit,
            [EnemyId.BlazeGoblin] = Species.Spirit,
            [EnemyId.BlazeGoblinFighter] = Species.Spirit,
            [EnemyId.BlazeGoblinLeader] = Species.Spirit,
            [EnemyId.BlazeGoblinSling] = Species.Spirit,
            [EnemyId.BlazeGrigori] = Species.Spirit,
            [EnemyId.BlazeHarpy] = Species.Spirit,
            [EnemyId.BlazeWolf] = Species.Spirit,
            [EnemyId.Blob] = Species.Formless,
            [EnemyId.BlueNewt] = Species.DemiHuman,
            [EnemyId.BluntSoldierDwarfOrc] = Species.Demonkin,
            [EnemyId.Boar] = Species.Beast,
            [EnemyId.BoltCorpsePunisher] = Species.Undead,
            [EnemyId.BoltCorpseTorturer] = Species.Undead,
            [EnemyId.BoltGrimwarg] = Species.Beast,
            [EnemyId.BoltMachina] = Species.Construct,
            [EnemyId.BoltMachinaTrinity] = Species.Construct,
            [EnemyId.BoltSkeleton] = Species.Skeletal,
            [EnemyId.BoltSkeletonBrute] = Species.Skeletal,
            [EnemyId.BoltSkeletonCyclops] = Species.Skeletal,
            [EnemyId.BruteApe] = Species.Demonkin,
            [EnemyId.Buck] = Species.Beast,
            [EnemyId.BurnedEnt] = Species.Giant,
            [EnemyId.CaptainAncestorOrc] = Species.Demonkin,
            [EnemyId.CaptainOrc0] = Species.Demonkin,
            [EnemyId.CaptainOrc1] = Species.Demonkin,
            [EnemyId.Catoblepas] = Species.WarReady,
            [EnemyId.ChickenBrown] = Species.Beast,
            [EnemyId.ChickenWhite] = Species.Beast,
            [EnemyId.Chimera0] = Species.Beast,
            [EnemyId.Chimera1] = Species.Beast,
            [EnemyId.Cockatrice] = Species.Winged,
            [EnemyId.Colossus0] = Species.Giant,
            [EnemyId.Colossus1] = Species.Giant,
            [EnemyId.Colossus2] = Species.Giant,
            [EnemyId.Cragger] = Species.Demonkin,
            [EnemyId.CrystalEye] = Species.Demon,
            [EnemyId.CrystalOfBlessing] = Species.Unknown,
            [EnemyId.CursedDragon] = Species.Dragonkin,
            [EnemyId.Cyclops0] = Species.Giant,
            [EnemyId.Cyclops1] = Species.Giant,
            [EnemyId.Cyclops2] = Species.Giant,
            [EnemyId.Cyclops3] = Species.Giant,
            [EnemyId.Cyclops4] = Species.Giant,
            [EnemyId.Cyclops5] = Species.Giant,
            [EnemyId.CyclopsClub] = Species.Giant,
            [EnemyId.CyclopsGiant] = Species.Giant,
            [EnemyId.Dagon] = Species.Dragonkin,
            [EnemyId.DamnedGoblin] = Species.Alchemized,
            [EnemyId.DamnedGoblinFighter] = Species.Alchemized,
            [EnemyId.DamnedGolem] = Species.Alchemized,
            [EnemyId.DamnedSlingGoblinFlask] = Species.Alchemized,
            [EnemyId.DamnedWolf] = Species.Alchemized,
            [EnemyId.DarkCorpsePunisher] = Species.Undead,
            [EnemyId.DarkCorpseTorturer] = Species.Undead,
            [EnemyId.DarkSkeleton] = Species.Skeletal,
            [EnemyId.DarkSkeletonBrute] = Species.Skeletal,
            [EnemyId.Death] = Species.Spirit,
            [EnemyId.DeathKnight] = Species.Spirit,
            [EnemyId.DeepSlime] = Species.Formless,
            [EnemyId.Diamantes] = Species.Alchemized, //Alchemized?
            [EnemyId.DiamantesHuman] = Species.Human,
            [EnemyId.DimSlime] = Species.Formless,
            [EnemyId.Direwolf] = Species.Beast,
            [EnemyId.Doe] = Species.Beast,
            [EnemyId.DragonCrystalOfBindingBlackDragon] = Species.Unknown,
            [EnemyId.DragonCrystalOfDarknessFlyingUntranslated] = Species.Unknown,
            [EnemyId.DragonCrystalOfDarknessInvulnerableFlying] = Species.Unknown,
            [EnemyId.DragonCrystalOfDarknessInvulnerableGround] = Species.Unknown,
            [EnemyId.DragonCrystalOfDestruction] = Species.Unknown,
            [EnemyId.DragonCrystalOfDestructionLotsOfLaserRocksAndBigExplosion] = Species.Unknown,
            [EnemyId.DragonCrystalOfDestructionShootsLaserRocks] = Species.Unknown,
            [EnemyId.DragonCrystalOfDestructionSucksYouInWithMagic0] = Species.Unknown,
            [EnemyId.DragonCrystalOfDestructionSucksYouInWithMagic1] = Species.Unknown,
            [EnemyId.DragonCrystalOfGroaningSpiritDragonWillmiaWm] = Species.Unknown,
            [EnemyId.DragonCrystalOfPrayingSpiritDragonWillmiaWm] = Species.Unknown,
            [EnemyId.DragonCrystalTheEvilDragonWmUntranslated] = Species.Unknown,
            [EnemyId.Drake0] = Species.Dragonkin,
            [EnemyId.Drake1] = Species.Dragonkin,
            [EnemyId.DreadApe] = Species.Demonkin,
            [EnemyId.DwarfOrcTest] = Species.Demonkin,
            [EnemyId.ElderDragon0] = Species.Dragonkin,
            [EnemyId.ElderDragon1] = Species.Dragonkin,
            [EnemyId.ElderDragonEpitathRoadTrial] = Species.Dragonkin,
            [EnemyId.ElectricSlime] = Species.Formless,
            [EnemyId.Eliminator] = Species.Undead,
            [EnemyId.EliminatorSlay] = Species.Undead,
            [EnemyId.EmeraldEye] = Species.Demon,
            [EnemyId.EmpressGhost] = Species.Spirit,
            [EnemyId.EmptyNoEnemy0] = Species.Unknown,
            [EnemyId.EmptyNoEnemy1] = Species.Unknown,
            [EnemyId.EmptyNoEnemy2] = Species.Unknown,
            [EnemyId.Ent] = Species.Giant,
            [EnemyId.EvilEye0] = Species.Demon,
            [EnemyId.EvilEye1] = Species.Demon,
            [EnemyId.FlameCorpsePunisher] = Species.Undead,
            [EnemyId.FlameCorpseTorturer] = Species.Undead,
            [EnemyId.FlameSkeleton] = Species.Skeletal,
            [EnemyId.FlameSkeletonBrute] = Species.Skeletal,
            [EnemyId.FlameSkeletonCyclops] = Species.Skeletal,
            [EnemyId.Fodden] = Species.Giant,
            [EnemyId.FootBiter] = Species.Beast,
            [EnemyId.ForestGoblin] = Species.DemiHuman,
            [EnemyId.ForestGoblinFighter] = Species.DemiHuman,
            [EnemyId.FormerCommanderLeoFinalBoss] = Species.Human,
            [EnemyId.FreezingSlime] = Species.Formless,
            [EnemyId.FrogBlue] = Species.Beast,
            [EnemyId.FrogGold] = Species.Beast,
            [EnemyId.FrostCorpsePunisher] = Species.Undead,
            [EnemyId.FrostCorpseTorturer] = Species.Undead,
            [EnemyId.FrostMachina] = Species.Construct,
            [EnemyId.FrostMachinaTrinity] = Species.Construct,
            [EnemyId.FrostSkeleton] = Species.Skeletal,
            [EnemyId.FrostSkeletonBrute] = Species.Skeletal,
            [EnemyId.FrostSkeletonCyclops] = Species.Skeletal,
            [EnemyId.Gargoyle] = Species.Construct,
            [EnemyId.GeneralOrc] = Species.Demonkin,
            [EnemyId.GeoGolem] = Species.Construct,
            [EnemyId.GeoSaurian] = Species.DemiHuman,
            [EnemyId.Ghost] = Species.Spirit,
            [EnemyId.GhostMail] = Species.Spirit,
            [EnemyId.Ghoul0] = Species.Demonkin,
            [EnemyId.Ghoul1] = Species.Demonkin,
            [EnemyId.GiantGeoSaurian] = Species.DemiHuman,
            [EnemyId.GiantRat] = Species.Beast,
            [EnemyId.GiantSaurian] = Species.DemiHuman,
            [EnemyId.GiantSaurianSage] = Species.DemiHuman,
            [EnemyId.GiantSulfurSaurian] = Species.DemiHuman,
            [EnemyId.GiantUnspeakableMeat] = Species.Alchemized,
            [EnemyId.GigantMachina] = Species.Construct,
            [EnemyId.GigantMachinaTrinity] = Species.Construct,
            [EnemyId.GluttonOoze] = Species.Formless,
            [EnemyId.Goat] = Species.Beast,
            [EnemyId.Goblin] = Species.DemiHuman,
            [EnemyId.GoblinAidShaman] = Species.DemiHuman,
            [EnemyId.GoblinBomber] = Species.DemiHuman,
            [EnemyId.GoblinFighter0] = Species.DemiHuman,
            [EnemyId.GoblinFighter1] = Species.DemiHuman,
            [EnemyId.GoblinFighter2] = Species.DemiHuman,
            [EnemyId.GoblinFighter3] = Species.DemiHuman,
            [EnemyId.GoblinFighter4] = Species.DemiHuman,
            [EnemyId.GoblinFighter5] = Species.DemiHuman,
            [EnemyId.GoblinFighter6] = Species.DemiHuman,
            [EnemyId.GoblinFighter7] = Species.DemiHuman,
            [EnemyId.GoblinFighter8] = Species.DemiHuman,
            [EnemyId.GoblinFighter9] = Species.DemiHuman,
            [EnemyId.GoblinFighter10] = Species.DemiHuman,
            [EnemyId.GoblinHorn] = Species.DemiHuman,
            [EnemyId.GoblinKingNpc] = Species.DemiHuman,
            [EnemyId.GoblinLeader] = Species.DemiHuman,
            [EnemyId.GoblinShaman] = Species.DemiHuman,
            [EnemyId.Golem] = Species.Construct,
            [EnemyId.Golgorran0] = Species.Dragonkin,
            [EnemyId.Golgorran1] = Species.Dragonkin,
            [EnemyId.Goliath] = Species.Alchemized,
            [EnemyId.GoliathCyclopsTest] = Species.Alchemized,
            [EnemyId.Gorechimera0] = Species.Beast,
            [EnemyId.Gorechimera1] = Species.Beast,
            [EnemyId.Gorecyclops0] = Species.Giant,
            [EnemyId.Gorecyclops1] = Species.Giant,
            [EnemyId.Gorecyclops2] = Species.Giant,
            [EnemyId.Goremanticore] = Species.Demon,
            [EnemyId.Gorgon] = Species.Demon,
            [EnemyId.GrandEnt0] = Species.Giant,
            [EnemyId.GrandEnt1] = Species.Giant,
            [EnemyId.GrandEnt2] = Species.Giant,
            [EnemyId.GreaterGoblinSword] = Species.DemiHuman,
            [EnemyId.GreaterGoblinTorch] = Species.DemiHuman,
            [EnemyId.GreenGuardian] = Species.Beast,
            [EnemyId.Griffin0] = Species.Winged,
            [EnemyId.Griffin1] = Species.Winged,
            [EnemyId.Grigori] = Species.Demon,
            [EnemyId.GrimGoblin] = Species.DemiHuman,
            [EnemyId.GrimGoblinFighter] = Species.DemiHuman,
            [EnemyId.GrimGoblinLeader] = Species.DemiHuman,
            [EnemyId.Grimwarg] = Species.Beast,
            [EnemyId.GrudgeGhost] = Species.Cursed,
            [EnemyId.Habanero] = Species.DemiHuman,
            [EnemyId.Harpy] = Species.Winged,
            [EnemyId.HeavySoldierDwarfOrc] = Species.Demonkin,
            [EnemyId.Hellhound] = Species.Demon,
            [EnemyId.HighPixieBiff] = Species.DemiHuman,
            [EnemyId.HighPixiePow] = Species.DemiHuman,
            [EnemyId.HighPixieZolda] = Species.DemiHuman,
            [EnemyId.Hobgoblin] = Species.DemiHuman,
            [EnemyId.HobgoblinFighter] = Species.DemiHuman,
            [EnemyId.HobgoblinLeader] = Species.DemiHuman,
            [EnemyId.HoodedIris] = Species.Human,
            [EnemyId.Ifrit1stForm] = Species.Demon,
            [EnemyId.Ifrit2ndForm] = Species.Demon,
            [EnemyId.InfectedBehemoth] = Species.Infected,
            [EnemyId.InfectedDirewolf] = Species.Infected,
            [EnemyId.InfectedGorecyclops] = Species.Infected,
            [EnemyId.InfectedGriffin] = Species.Infected,
            [EnemyId.InfectedHobgoblin] = Species.Infected,
            [EnemyId.InfectedHobgoblinFighter] = Species.Infected,
            [EnemyId.InfectedOrcAimer] = Species.Infected,
            [EnemyId.InfectedOrcBanger] = Species.Infected,
            [EnemyId.InfectedOrcSoldier] = Species.Infected,
            [EnemyId.InfectedSlingHobgoblin] = Species.Infected,
            [EnemyId.InfectedSnowHarpy] = Species.Infected,
            [EnemyId.Iris] = Species.Human,
            [EnemyId.KillerBee] = Species.Winged,
            [EnemyId.LapisEye] = Species.Demon,
            [EnemyId.LargeNewt] = Species.DemiHuman,
            [EnemyId.Leech] = Species.Formless,
            [EnemyId.Legion] = Species.Demon,
            [EnemyId.LegionDifferentBones] = Species.Demon,
            [EnemyId.LegionFighter] = Species.Demon,
            [EnemyId.LegionLeader] = Species.Demon,
            [EnemyId.Leo] = Species.Human,
            [EnemyId.Lindwurm0] = Species.Dragonkin,
            [EnemyId.Lindwurm1] = Species.Dragonkin,
            [EnemyId.LittleCrag] = Species.Demonkin,
            [EnemyId.LittleSpine] = Species.Demonkin,
            [EnemyId.LivingArmor] = Species.Spirit,
            [EnemyId.LotusFin] = Species.Dragonkin,
            [EnemyId.LuxCorpsePunisher] = Species.Undead,
            [EnemyId.LuxCorpseTorturer] = Species.Undead,
            [EnemyId.LuxSkeleton] = Species.Skeletal,
            [EnemyId.LuxSkeletonBrute] = Species.Skeletal,
            [EnemyId.Mandragora] = Species.DemiHuman,
            [EnemyId.MandragoraFlower] = Species.DemiHuman,
            [EnemyId.Maneater] = Species.Demon,
            [EnemyId.ManeaterClosed] = Species.Demon,
            [EnemyId.Manticore0] = Species.Demon,
            [EnemyId.Manticore1] = Species.Demon,
            [EnemyId.Medusa] = Species.Demon,
            [EnemyId.MegadoGuardFighter] = Species.Human,
            [EnemyId.MegadoGuardHunter] = Species.Human,
            [EnemyId.MegadoGuardSeeker] = Species.Human,
            [EnemyId.MegadoGuardWarrior] = Species.Human,
            [EnemyId.MerganDefender] = Species.Human,
            [EnemyId.MerganElementArcher] = Species.Human,
            [EnemyId.MerganFighter] = Species.Human,
            [EnemyId.MerganHealer] = Species.Human,
            [EnemyId.MerganHunter] = Species.Human,
            [EnemyId.MerganMage] = Species.Human,
            [EnemyId.MerganSeeker] = Species.Human,
            [EnemyId.MerganWarrior] = Species.Human,
            [EnemyId.Merman] = Species.DemiHuman,
            [EnemyId.MiseryGhost] = Species.Spirit,
            [EnemyId.MistDrake] = Species.Spirit,
            [EnemyId.MistFighter] = Species.Spirit,
            [EnemyId.MistHunter] = Species.Spirit,
            [EnemyId.MistPriest] = Species.Spirit,
            [EnemyId.MistSorcerer] = Species.Spirit,
            [EnemyId.MistWarrior] = Species.Spirit,
            [EnemyId.MistWyrm] = Species.Spirit,
            [EnemyId.Mogok] = Species.Demonkin,
            [EnemyId.MoleTroll0] = Species.Giant,
            [EnemyId.MoleTroll1] = Species.Giant,
            [EnemyId.MothCyanSleep] = Species.Winged,
            [EnemyId.MothMagentaPoison] = Species.Winged,
            [EnemyId.Mudman] = Species.Formless,
            [EnemyId.NecroMaster] = Species.Demonkin,
            [EnemyId.Nightmare] = Species.Winged,
            [EnemyId.NoEnemyInCombat0] = Species.Unknown,
            [EnemyId.NoEnemyInCombat1] = Species.Unknown,
            [EnemyId.NoEnemyInCombat2] = Species.Unknown,
            [EnemyId.Ogre] = Species.Demonkin,
            [EnemyId.OilJelly] = Species.Formless,
            [EnemyId.Ooze] = Species.Formless,
            [EnemyId.OrcAimer] = Species.Demonkin,
            [EnemyId.OrcBanger] = Species.Demonkin,
            [EnemyId.OrcBattler] = Species.Demonkin,
            [EnemyId.OrcBringer] = Species.Demonkin,
            [EnemyId.OrcGoblinTest] = Species.Demonkin,
            [EnemyId.OrcSoldier0] = Species.Demonkin,
            [EnemyId.OrcSoldier1] = Species.Demonkin,
            [EnemyId.OrcSoldier2] = Species.Demonkin,
            [EnemyId.OrcSoldier3] = Species.Demonkin,
            [EnemyId.OrcSoldier4] = Species.Demonkin,
            [EnemyId.OrcTrooper] = Species.Demonkin,
            [EnemyId.Ox] = Species.Beast,
            [EnemyId.PawnDefender] = Species.Human,
            [EnemyId.PawnElementArcher] = Species.Human,
            [EnemyId.PawnFighter] = Species.Human,
            [EnemyId.PawnHealer] = Species.Human,
            [EnemyId.PawnHunter] = Species.Human,
            [EnemyId.PawnMage] = Species.Human,
            [EnemyId.PawnSeeker] = Species.Human,
            [EnemyId.PawnWarrior] = Species.Human,
            [EnemyId.PhindymianDefender] = Species.Human,
            [EnemyId.PhindymianElementArcher] = Species.Human,
            [EnemyId.PhindymianEnt0] = Species.Giant,
            [EnemyId.PhindymianEnt1] = Species.Giant,
            [EnemyId.PhindymianFighter] = Species.Human,
            [EnemyId.PhindymianHunter] = Species.Human,
            [EnemyId.PhindymianPriest] = Species.Human,
            [EnemyId.PhindymianSeeker] = Species.Human,
            [EnemyId.PhindymianSorcerer] = Species.Human,
            [EnemyId.PhindymianWarrior] = Species.Human,
            [EnemyId.PhotonSlime] = Species.Formless,
            [EnemyId.Pig] = Species.Beast,
            [EnemyId.PigDirty] = Species.Beast,
            [EnemyId.Piglet] = Species.Beast,
            [EnemyId.PigletDirty] = Species.Beast,
            [EnemyId.Pixie] = Species.DemiHuman,
            [EnemyId.PixieBiff] = Species.DemiHuman,
            [EnemyId.PixieDin] = Species.DemiHuman,
            [EnemyId.PixieJabber] = Species.DemiHuman,
            [EnemyId.PixieKing] = Species.DemiHuman,
            [EnemyId.PixiePow] = Species.DemiHuman,
            [EnemyId.PoisonMerman] = Species.DemiHuman,
            [EnemyId.PyreSaurianSalamander] = Species.DemiHuman,
            [EnemyId.PyroSlime] = Species.Formless,
            [EnemyId.Rabbit] = Species.Beast,
            [EnemyId.RageGhost] = Species.Spirit,
            [EnemyId.RangedSoldierDwarfOrc] = Species.Demonkin,
            [EnemyId.RedZuhl] = Species.Demon,
            [EnemyId.Redcap] = Species.DemiHuman,
            [EnemyId.RedcapFighter] = Species.DemiHuman,
            [EnemyId.RockSaurian] = Species.DemiHuman,
            [EnemyId.RockSaurianSpinel] = Species.DemiHuman,
            [EnemyId.RockTheEvilDragonWm] = Species.Dragonkin,
            [EnemyId.RogueDefender] = Species.Human,
            [EnemyId.RogueFighter] = Species.Human,
            [EnemyId.RogueHealer] = Species.Human,
            [EnemyId.RogueHunter] = Species.Human,
            [EnemyId.RogueMage] = Species.Human,
            [EnemyId.RogueSeeker] = Species.Human,
            [EnemyId.RogueWarrior] = Species.Human,
            [EnemyId.RubyEye] = Species.Demon,
            [EnemyId.Samyaza] = Species.Demon,
            [EnemyId.Saurian] = Species.DemiHuman,
            [EnemyId.SaurianSage] = Species.DemiHuman,
            [EnemyId.ScarletDefender] = Species.Human,
            [EnemyId.ScarletFighter] = Species.Human,
            [EnemyId.ScarletHealer] = Species.Human,
            [EnemyId.ScarletHunter] = Species.Human,
            [EnemyId.ScarletMage] = Species.Human,
            [EnemyId.ScarletSeeker] = Species.Human,
            [EnemyId.ScarletWarrior] = Species.Human,
            [EnemyId.Scourge0] = Species.Infected,
            [EnemyId.Scourge1] = Species.Infected,
            [EnemyId.SeverelyInfectedBehemoth] = Species.Infected,
            [EnemyId.SeverelyInfectedDemon] = Species.Infected,
            [EnemyId.SeverelyInfectedGorecyclops] = Species.Infected,
            [EnemyId.SeverelyInfectedGriffin] = Species.Infected,
            [EnemyId.SeverelyInfectedPixie] = Species.Infected,
            [EnemyId.SeverelyInfectedPixieClub] = Species.Infected,
            [EnemyId.SeverelyInfectedPixieCorruptionSeeds] = Species.Infected,
            [EnemyId.SeverelyInfectedScourge] = Species.Infected,
            [EnemyId.SeverelyInfectedStymphalides] = Species.Infected,
            [EnemyId.SeverelyInfectedWarg] = Species.Infected,
            [EnemyId.ShadowChimera] = Species.Cursed,
            [EnemyId.ShadowGoblin] = Species.Cursed,
            [EnemyId.ShadowGoblinFighter] = Species.Cursed,
            [EnemyId.ShadowGoblinLeader] = Species.Cursed,
            [EnemyId.ShadowGrigori] = Species.Cursed,
            [EnemyId.ShadowHarpy] = Species.Cursed,
            [EnemyId.ShadowMasterGiant] = Species.Cursed,
            [EnemyId.ShadowMasterInvulnerable] = Species.Cursed,
            [EnemyId.ShadowSlingGoblin] = Species.Cursed,
            [EnemyId.ShadowWolf] = Species.Cursed,
            [EnemyId.ShieldGoblin] = Species.DemiHuman,
            [EnemyId.SilverRoar] = Species.Demonkin,
            [EnemyId.Siren] = Species.Winged,
            [EnemyId.Skeleton] = Species.Skeletal,
            [EnemyId.SkeletonBrute] = Species.Skeletal,
            [EnemyId.SkeletonCyclops] = Species.Skeletal,
            [EnemyId.SkeletonCyclopsTest] = Species.Skeletal,
            [EnemyId.SkeletonKnight] = Species.Skeletal,
            [EnemyId.SkeletonLordAbyss] = Species.Skeletal,
            [EnemyId.SkeletonMage0] = Species.Skeletal,
            [EnemyId.SkeletonMage1] = Species.Skeletal,
            [EnemyId.SkeletonMageDifferentAi] = Species.Skeletal,
            [EnemyId.SkeletonSorcerer0] = Species.Skeletal,
            [EnemyId.SkeletonSorcerer1] = Species.Skeletal,
            [EnemyId.SkeletonSorcerer2] = Species.Skeletal,
            [EnemyId.SkeletonSorcerer3] = Species.Skeletal,
            [EnemyId.SkeletonWarg] = Species.Skeletal,
            [EnemyId.SkeletonWarrior] = Species.Skeletal,
            [EnemyId.SkullLord] = Species.Skeletal,
            [EnemyId.Slime] = Species.Formless,
            [EnemyId.SlingForestGoblin] = Species.DemiHuman,
            [EnemyId.SlingGoblinRock] = Species.DemiHuman,
            [EnemyId.SlingGoblinTorch] = Species.DemiHuman,
            [EnemyId.SlingGrimGoblinOilFlask] = Species.DemiHuman,
            [EnemyId.SlingHobgoblinOilFlask] = Species.DemiHuman,
            [EnemyId.SlingHobgoblinTorch] = Species.DemiHuman,
            [EnemyId.SlingRedcap] = Species.DemiHuman,
            [EnemyId.Sludgeman] = Species.Formless,
            [EnemyId.Snake] = Species.Beast,
            [EnemyId.SnowHarpy] = Species.Winged,
            [EnemyId.Sphinx0] = Species.Winged,
            [EnemyId.Sphinx1] = Species.Winged,
            [EnemyId.Spider] = Species.Beast,
            [EnemyId.Spineback0] = Species.Demonkin,
            [EnemyId.Spineback1] = Species.Demonkin,
            [EnemyId.Spineback2] = Species.Demonkin,
            [EnemyId.SpiritDragonWillmia0] = Species.Dragonkin,
            [EnemyId.SpiritDragonWillmia1] = Species.Dragonkin,
            [EnemyId.SpiritDragonWillmiaActive] = Species.Dragonkin,
            [EnemyId.SpiritDragonWillmiaGoblinTest] = Species.Dragonkin,
            [EnemyId.SpiritDragonWillmiaTest] = Species.Dragonkin,
            [EnemyId.SquadLeaderDwarfOrc] = Species.Demonkin,
            [EnemyId.StoneBlob] = Species.Formless,
            [EnemyId.StoutUndead] = Species.Undead,
            [EnemyId.Strix] = Species.Winged,
            [EnemyId.Stymphalides] = Species.Winged,
            [EnemyId.SulfurSaurian] = Species.DemiHuman,
            [EnemyId.SwordSoldierDwarfOrc] = Species.Demonkin,
            [EnemyId.SwordUndead] = Species.Undead,
            [EnemyId.Tarasque] = Species.Dragonkin,
            [EnemyId.TarasqueGoblinTest] = Species.Dragonkin,
            [EnemyId.TentacleEvilEye0] = Species.Demon,
            [EnemyId.TentacleEvilEye1] = Species.Demon,
            [EnemyId.TentacleVoltEye0] = Species.Demon,
            [EnemyId.TentacleVoltEye1] = Species.Demon,
            [EnemyId.TheEvilDragon0] = Species.Dragonkin,
            [EnemyId.TheEvilDragon1] = Species.Dragonkin,
            [EnemyId.TheEvilDragonSparks] = Species.Dragonkin,
            [EnemyId.TotemShadowMasterWmUntranslated] = Species.Cursed,
            [EnemyId.Troll] = Species.Giant,
            [EnemyId.Ukobach] = Species.Construct,
            [EnemyId.UndeadFemale] = Species.Undead,
            [EnemyId.UndeadMale] = Species.Undead,
            [EnemyId.UnspeakableMeat] = Species.Alchemized,
            [EnemyId.Ushumgal] = Species.Dragonkin,
            [EnemyId.Valefar] = Species.Beast,
            [EnemyId.VileEye] = Species.Demon,
            [EnemyId.VoltEye] = Species.Demon,
            [EnemyId.WarMaster0] = Species.Demonkin,
            [EnemyId.WarMaster1] = Species.Demonkin,
            [EnemyId.WarReadyGiantSaurianLightArmor] = Species.WarReady,
            [EnemyId.WarReadyGorecyclopsLightArmor0] = Species.WarReady,
            [EnemyId.WarReadyGorecyclopsLightArmor1] = Species.WarReady,
            [EnemyId.WarReadyGoremanticoreLightArmor] = Species.WarReady,
            [EnemyId.WarReadyGrimwargLightArmor] = Species.WarReady,
            [EnemyId.WarReadyNightmareLightArmor] = Species.WarReady,
            [EnemyId.WarReadyOgreLightArmor] = Species.WarReady,
            [EnemyId.WarReadySaurianLightArmor] = Species.WarReady,
            [EnemyId.Warg] = Species.Beast,
            [EnemyId.WarriorUndead] = Species.Undead,
            [EnemyId.WhiteChimera0] = Species.Beast,
            [EnemyId.WhiteChimera1] = Species.Beast,
            [EnemyId.WhiteDragon] = Species.Dragonkin,
            [EnemyId.WhiteDragonNpc] = Species.Dragonkin,
            [EnemyId.WhiteGriffin0] = Species.Winged,
            [EnemyId.WhiteGriffin1] = Species.Winged,
            [EnemyId.WhiteTarasque] = Species.Dragonkin,
            [EnemyId.Wight0] = Species.Skeletal,
            [EnemyId.Wight1] = Species.Skeletal,
            [EnemyId.WildBoarBrown] = Species.Beast,
            [EnemyId.WildBoarStripes] = Species.Beast,
            [EnemyId.WisenedTarasque0] = Species.Dragonkin,
            [EnemyId.WisenedTarasque1] = Species.Dragonkin,
            [EnemyId.Witch] = Species.Spirit,
            [EnemyId.Wolf] = Species.Beast,
            [EnemyId.Worm] = Species.Formless,
            [EnemyId.Wyrm0] = Species.Dragonkin,
            [EnemyId.Wyrm1] = Species.Dragonkin,
            [EnemyId.Zuhl0] = Species.Demon,
            [EnemyId.Zuhl1] = Species.Demon,
            [EnemyId.Zuhl2] = Species.Demon,
            [EnemyId.ZuhlPassive] = Species.Demon,
        };
    }
}
