namespace Arrowgene.Ddon.Shared.Model
{
    public enum ItemSubCategory : ushort //For serverside use only.
    {
        None = 0,

        UseNone = 1,
        UseThrowing = 2,
        UseMine = 3,
        UseLumber = 4,
        UseLockpick = 5,
        UseJobItem = 6,
        UseDoorKey = 8,

        //MaterialCategory, offset by 100
        MaterialCategoryOffset = 100,
        MaterialInorganicMetal = 101,
        MaterialInorganicOre = 102,
        MaterialInorganicSand = 103,
        MaterialSewingCloth = 104,
        MaterialSewingString = 105,
        MaterialSewingFur = 106,
        MaterialAnimalSkin = 107,
        MaterialAnimalBone = 108,
        MaterialAnimalFang = 109,
        MaterialAnimalHorn = 110,
        MaterialUnusedShell = 111,
        MaterialAnimalFeather = 112,
        MaterialInorganicGem = 113,
        MaterialPlantGrass = 114,
        MaterialPlantMushroom = 117,
        MaterialPlantLumber = 118,
        MaterialInorganicLiquid = 119,
        MaterialSpecialScroll = 120,
        MaterialAnimalMeat = 122,
        MaterialSpecialOther = 123,
        MaterialCrestWeapon = 124,
        MaterialCrestArmor = 125,
        MaterialRefiningWeapon = 126,
        MaterialRefiningArmor = 127,
        MaterialSpecialDye = 128,
        MaterialAppraisedItem = 129,
        MaterialRegionalMaterial = 130,
        MaterialSlayerStone = 131,
        MaterialPawnInspiration = 132,
        MaterialDragonAbility = 133,

        //WeaponCategory, offset by 200
        WeaponCategoryOffset = 200,
        WeaponHand = 200,
        WeaponSword = 201,
        WeaponShield = 202,
        WeaponGreatsword = 203,
        WeaponGreatshield = 204,
        WeaponRod = 205,
        WeaponDagger = 206,
        WeaponBow = 207,
        WeaponGauntlet = 208,
        WeaponMagickBow = 209,
        WeaponStaff = 211,
        WeaponArchistaff = 212,
        WeaponLance = 213,
        WeaponMagickSword = 215,

        //EquipSlot, offset by 300
        EquipSlotOffset = 300,
        EquipArmorHelm = 303,
        EquipArmorBody = 304,
        EquipClothingBody = 305,
        EquipArmorArm = 306,
        EquipArmorLeg = 307,
        EquipClothingLeg = 308,
        EquipOverwear = 309,
        EquipJewelry = 310,
        EquipLantern = 311,
        EquipEnsemble = 312,

        //JewelrySubCategory, offset by 400
        JewelrySubCategoryOffset = 400,
        JewelryCommon = 426,
        JewelryRing = 442,
        JewelryBracelet = 458,
        JewelryPierce = 474,
        EmblemStone = 490,
    }
}
