using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Arrowgene.Ddon.Shared.Model
{
    public enum NpcFunction : uint
    {
        GeneralShop = 3, // FUNC_SELECT_NAME_3, ショップ,
        ItemShop = 4, // FUNC_SELECT_NAME_4, ショップ,
        EquipmentShop = 5, // FUNC_SELECT_NAME_5, ショップ,
        MaterialShop = 6, // FUNC_SELECT_NAME_6, ショップ,
        Inn = 7,  // FUNC_SELECT_NAME_7, 宿泊,
        WeaponShop = 8, // FUNC_SELECT_NAME_8, ショップ,
        ArmorShop = 9, // FUNC_SELECT_NAME_9, ショップ,
        ArtsSupport = 10, // FUNC_SELECT_NAME_10, 戦技の付替え,
        VocationArtsSupport = 11, // FUNC_SELECT_NAME_11, 転職／戦技の付替え,
        GrandMission = 12, // FUNC_SELECT_NAME_12, グランドミッション,
        PartyOrganization = 13, // FUNC_SELECT_NAME_13, パーティー編成,
        ClanManagement = 14, // FUNC_SELECT_NAME_14, クラン設立・加入,
        Craft = 15, // FUNC_SELECT_NAME_15, クラフト,
        BeautySalon = 16, // FUNC_SELECT_NAME_16, 美容院,
        LestaniaNews = 17, // FUNC_SELECT_NAME_17, レスタニアニュース,
        DragonForceAugmentation = 18, // FUNC_SELECT_NAME_18, 竜力の継承,
        OrbExchangeCrests = 19, // FUNC_SELECT_NAME_19, オーブ交換：クレスト,
        OrbExchangeRareItemsMaterials = 20, // FUNC_SELECT_NAME_20, オーブ交換：珍品／素材,
        AreaInformation = 21, // FUNC_SELECT_NAME_21, エリア情報,
        JobTraining = 22, // FUNC_SELECT_NAME_22, ジョブ修練,
        Unknown23 = 23,
        Bazaar = 24, // FUNC_SELECT_NAME_24,バザー Bazaar,
        StorageBox = 25, // FUNC_SELECT_NAME_25,
        DeliveryBox = 26, // FUNC_SELECT_NAME_26,
        RiftStone = 27, // FUNC_SELECT_NAME_27,
        DragonsKeystone0 = 28, // FUNC_SELECT_NAME_28,
        PortCrystal = 29, // FUNC_SELECT_NAME_29,
        DragonsKeystone1 = 30, // FUNC_SELECT_NAME_30,
        QuestBoard = 31, // FUNC_SELECT_NAME_31,
        ClanQuestBoard = 32, // FUNC_SELECT_NAME_32,
        RankingBoard = 33, // FUNC_SELECT_NAME_33,
        LostCitysKeystone = 34, // FUNC_SELECT_NAME_34,
        BondTransfer = 35, // FUNC_SELECT_NAME_35,
        ReviewReports = 36, // FUNC_SELECT_NAME_36, 報告書の確認, (Historian?)
        RevivePawn = 37, // FUNC_SELECT_NAME_37, ポーンの復活,
        ExtremeMissions = 39, // FUNC_SELECT_NAME_39, エクストリームミッション,
        RecoverRevivalPower = 40, // FUNC_SELECT_NAME_40, 復活力の回復,
        CampStorage = 41, // FUNC_SELECT_NAME_41,,
        LoginStamp = 42, // FUNC_SELECT_NAME_42, ログインスタンプ,
        ReceiveReward = 43, // FUNC_SELECT_NAME_43, 報酬受け取り,
        TreasureLot = 44, // FUNC_SELECT_NAME_44, トレジャーズロット,
        PawnManifest = 45, // FUNC_SELECT_NAME_45, 契約報酬の受け取り,
        TreatWeakness = 46, // FUNC_SELECT_NAME_46, 弱化の治療,
        MyrmidonsPledge = 47, // FUNC_SELECT_NAME_47, 戦徒の契り,
        AppraisalExchange = 48, // FUNC_SELECT_NAME_48, 鑑定交換,
        PartnerPawn = 49, // FUNC_SELECT_NAME_49, パートナーポーン,
        SkillAugmentation = 50, // FUNC_SELECT_NAME_50, 戦技の継承,
        Achievements = 51, // FUNC_SELECT_NAME_51, アチーブメント,
        StorageChest = 52, // FUNC_SELECT_NAME_52,,
        VocationUnlock = 53, // FUNC_SELECT_NAME_53, ジョブ解放,
        BoxTreasureLot = 54, // FUNC_SELECT_NAME_54, ボックストレジャーズロット,
        PawnExpeditionCorps = 55, // FUNC_SELECT_NAME_55, ポーン遠征隊,
        ConfirmExpeditionResults = 56, // FUNC_SELECT_NAME_56, 遠征結果の確認,
        PlayPointShop = 57, // FUNC_SELECT_NAME_57, プレイポイントショップ,
        ClanHallManagement = 58, // FUNC_SELECT_NAME_58, クラン拠点管理,
        WarfarePractice = 59, // FUNC_SELECT_NAME_59, 戦技練習,
        ClanDungeon = 60, // FUNC_SELECT_NAME_60, クランダンジョン,
        Present = 61, // FUNC_SELECT_NAME_61, プレゼント,
        PresentStatusCheck0 = 62, // FUNC_SELECT_NAME_62, プレゼント状況確認,
        PresentStatusCheck1 = 63, // FUNC_SELECT_NAME_63, プレゼント状況確認,
        SpecialSkillAugmentation = 64, // FUNC_SELECT_NAME_64, 絶技の継承,
        VocationEmblem = 65, // FUNC_SELECT_NAME_65, ジョブエンブレム,
        SubstoryLog = 66, // FUNC_SELECT_NAME_66, サブストーリーログ,
        HeroicSpiritSleepingPath = 67, // FUNC_SELECT_NAME_67, 英霊眠りし道,
        GiveSpirits = 68, // FUNC_SELECT_NAME_68, 魂を捧げる,
        WarMissions = 69, // FUNC_SELECT_NAME_69, ウォーミッション,
        DominionPointShop = 70, // FUNC_SELECT_NAME_70, ドミニオンポイントショップ,
        Reincarnation = 71, // FUNC_SELECT_NAME_71, 転生,
        CustomMadeArms = 72, // FUNC_SELECT_NAME_72, 武具のカスタムメイド,
        ArmsResourceDisassembly = 73, // FUNC_SELECT_NAME_73, 武具の資源分解,
        AdventurePassShop = 74, // FUNC_SELECT_NAME_74, 冒パスショップ,
        BecomeLv80= 75, // FUNC_SELECT_NAME_75, Lv.80にする,
        CompleteAugmentationofDragonForce = 76, // FUNC_SELECT_NAME_76, 竜力の継承を埋める,
        MakeAdventureEasier = 77, // FUNC_SELECT_NAME_77, 冒険をしやすくする,
        AchievementsRoyalFamilyRestoration = 78, // FUNC_SELECT_NAME_78, アチーブメント：王家再興,
        EmblemMedalExchange = 80, // FUNC_SELECT_NAME_80, 紋章メダル交換,
        OutingSupportService = 81, // FUNC_SELECT_NAME_81, おでかけ支援サービス,
        VisitAnothersRoom = 82, // FUNC_SELECT_NAME_82, 他人の自室訪問,
        SpecialQuestBoard = 83, // FUNC_SELECT_NAME_83,, (Large Delivery Reward Review?)
        PresentRewardReview = 84, // FUNC_SELECT_NAME_84, プレゼント報酬確認,
        MyRoomVisitSetup = 85, // FUNC_SELECT_NAME_85, 自室訪問設定,
        AdventureGuide = 86, // FUNC_SELECT_NAME_86, 冒険ガイド,
        RecruitmentBoard = 87, // FUNC_SELECT_NAME_87, 募集掲示板,
        BitterblackEquipmentEffectSeal = 88, // FUNC_SELECT_NAME_88, 黒呪装具の効果封印,
        BitterblackRareItemAppraisal = 89, // FUNC_SELECT_NAME_89, レアアイテムの鑑定,
        BitterblackItemTakeaway = 90, // FUNC_SELECT_NAME_90, 黒呪アイテムの持ち帰り,
        BitterblackReportSearchResults = 91, // FUNC_SELECT_NAME_91, 探索結果の報告,
        BecomeLv85Provisional = 93, // FUNC_SELECT_NAME_93, Lv.85にする（仮）,
        JobTrainingSkipProvisional = 94, // FUNC_SELECT_NAME_94, ジョブ修練スキップ（仮）,
        MedalExchange = 95, // FUNC_SELECT_NAME_95, 印記章交換,
        LargeDeliveryEvent = 96, // FUNC_SELECT_NAME_96, 大口納品イベント,
        BitterblackShop = 97, // FUNC_SELECT_NAME_97, 黒呪ショップ,
        ResetProgress = 98, // FUNC_SELECT_NAME_98, 進行のリセット,
        WildHunt = 99, // FUNC_SELECT_NAME_99, ワイルドハント,
        HighOrbExchange = 100, // FUNC_SELECT_NAME_100, ハイオーブ交換,
        DragonAbilitySynthesis = 101, // FUNC_SELECT_NAME_101, ドラゴンアビリティの合成,
        DragonArmorAppraisal = 102, // FUNC_SELECT_NAME_102, 竜防具の鑑定交換,
        RewardMission = 103, // FUNC_SELECT_NAME_103, リワードミッション,
        RewardMedalExchange = 104, // FUNC_SELECT_NAME_104, リワードメダル交換,
    }
}
