<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Arrowgene.Ddon.Metrics</RootNamespace>
        <Title>Dragons Dogma Online - Metrics</Title>
        <Company>DDON Team</Company>
        <Product>Ddon.Metrics</Product>
        <Version>$(Version)</Version>
        <Copyright>Copyright © 2019-2026 DDON Team</Copyright>
        <LangVersion>13</LangVersion>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
      <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
      <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
    </PropertyGroup>
    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>Arrowgene.Ddon.Server</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>
    <Import Project="./../SetSourceRevision.targets" />
    <ItemGroup>
        <PackageReference Include="Arrowgene.Networking" Version="2.1.7" />
    </ItemGroup>
</Project>
