using System.Collections.Generic;
using System.Linq;
using Arrowgene.Ddon.Server;
using Arrowgene.Ddon.Server.Network;
using Arrowgene.Ddon.Shared.Entity.PacketStructure;
using Arrowgene.Ddon.Shared.Entity.Structure;
using Arrowgene.Ddon.Shared.Model;
using Arrowgene.Ddon.Shared.Network;
using Arrowgene.Logging;

namespace Arrowgene.Ddon.GameServer.Handler
{
    public class SkillGetAcquirableSkillListHandler : StructurePacketHandler<GameClient, C2SSkillGetAcquirableSkillListReq>
    {
        private static readonly ServerLogger Logger = LogProvider.Logger<ServerLogger>(typeof(SkillGetCurrentSetSkillListHandler));

        public static readonly List<CDataSkillParam> AllSkills = new List<CDataSkillParam>() {
            // Fighter
            new CDataSkillParam() {SkillNo = 1, Job = JobId.Fighter},
            new CDataSkillParam() {SkillNo = 2, Job = JobId.Fighter},
            new CDataSkillParam() {SkillNo = 3, Job = JobId.Fighter},
            new CDataSkillParam() {SkillNo = 4, Job = JobId.Fighter},
            new CDataSkillParam() {SkillNo = 5, Job = JobId.Fighter},
            new CDataSkillParam() {SkillNo = 6, Job = JobId.Fighter},
            new CDataSkillParam() {SkillNo = 7, Job = JobId.Fighter},
            new CDataSkillParam() {SkillNo = 8, Job = JobId.Fighter},
            new CDataSkillParam() {SkillNo = 9, Job = JobId.Fighter},
            new CDataSkillParam() {SkillNo = 10, Job = JobId.Fighter},
            new CDataSkillParam() {SkillNo = 11, Job = JobId.Fighter},
            new CDataSkillParam() {SkillNo = 12, Job = JobId.Fighter},
            new CDataSkillParam() {SkillNo = 13, Job = JobId.Fighter},
            new CDataSkillParam() {SkillNo = 14, Job = JobId.Fighter},
            new CDataSkillParam() {SkillNo = 104, Job = JobId.Fighter},
            new CDataSkillParam() {SkillNo = 204, Job = JobId.Fighter},
            new CDataSkillParam() {SkillNo = 102, Job = JobId.Fighter},
            new CDataSkillParam() {SkillNo = 202, Job = JobId.Fighter},
            new CDataSkillParam() {SkillNo = 108, Job = JobId.Fighter},
            new CDataSkillParam() {SkillNo = 208, Job = JobId.Fighter},
            new CDataSkillParam() {SkillNo = 103, Job = JobId.Fighter},
            new CDataSkillParam() {SkillNo = 203, Job = JobId.Fighter},
            // Seeker
            new CDataSkillParam() {SkillNo = 1, Job = JobId.Seeker},
            new CDataSkillParam() {SkillNo = 2, Job = JobId.Seeker},
            new CDataSkillParam() {SkillNo = 3, Job = JobId.Seeker},
            new CDataSkillParam() {SkillNo = 4, Job = JobId.Seeker},
            new CDataSkillParam() {SkillNo = 5, Job = JobId.Seeker},
            new CDataSkillParam() {SkillNo = 6, Job = JobId.Seeker},
            new CDataSkillParam() {SkillNo = 7, Job = JobId.Seeker},
            new CDataSkillParam() {SkillNo = 8, Job = JobId.Seeker},
            new CDataSkillParam() {SkillNo = 9, Job = JobId.Seeker},
            new CDataSkillParam() {SkillNo = 10, Job = JobId.Seeker},
            new CDataSkillParam() {SkillNo = 11, Job = JobId.Seeker},
            new CDataSkillParam() {SkillNo = 12, Job = JobId.Seeker},
            new CDataSkillParam() {SkillNo = 13, Job = JobId.Seeker},
            new CDataSkillParam() {SkillNo = 14, Job = JobId.Seeker},
            new CDataSkillParam() {SkillNo = 112, Job = JobId.Seeker},
            new CDataSkillParam() {SkillNo = 212, Job = JobId.Seeker},
            new CDataSkillParam() {SkillNo = 113, Job = JobId.Seeker},
            new CDataSkillParam() {SkillNo = 213, Job = JobId.Seeker},
            new CDataSkillParam() {SkillNo = 107, Job = JobId.Seeker},
            new CDataSkillParam() {SkillNo = 207, Job = JobId.Seeker},
            new CDataSkillParam() {SkillNo = 102, Job = JobId.Seeker},
            new CDataSkillParam() {SkillNo = 202, Job = JobId.Seeker},
            // Hunter
            new CDataSkillParam() {SkillNo = 1, Job = JobId.Hunter},
            new CDataSkillParam() {SkillNo = 2, Job = JobId.Hunter},
            new CDataSkillParam() {SkillNo = 4, Job = JobId.Hunter},
            new CDataSkillParam() {SkillNo = 3, Job = JobId.Hunter},
            new CDataSkillParam() {SkillNo = 5, Job = JobId.Hunter},
            new CDataSkillParam() {SkillNo = 6, Job = JobId.Hunter},
            new CDataSkillParam() {SkillNo = 7, Job = JobId.Hunter},
            new CDataSkillParam() {SkillNo = 8, Job = JobId.Hunter},
            new CDataSkillParam() {SkillNo = 9, Job = JobId.Hunter},
            new CDataSkillParam() {SkillNo = 10, Job = JobId.Hunter},
            new CDataSkillParam() {SkillNo = 11, Job = JobId.Hunter},
            new CDataSkillParam() {SkillNo = 12, Job = JobId.Hunter},
            new CDataSkillParam() {SkillNo = 13, Job = JobId.Hunter},
            new CDataSkillParam() {SkillNo = 14, Job = JobId.Hunter},
            new CDataSkillParam() {SkillNo = 101, Job = JobId.Hunter},
            new CDataSkillParam() {SkillNo = 201, Job = JobId.Hunter},
            new CDataSkillParam() {SkillNo = 106, Job = JobId.Hunter},
            new CDataSkillParam() {SkillNo = 206, Job = JobId.Hunter},
            new CDataSkillParam() {SkillNo = 108, Job = JobId.Hunter},
            new CDataSkillParam() {SkillNo = 208, Job = JobId.Hunter},
            new CDataSkillParam() {SkillNo = 110, Job = JobId.Hunter},
            new CDataSkillParam() {SkillNo = 210, Job = JobId.Hunter},
            // Priest
            new CDataSkillParam() {SkillNo = 1, Job = JobId.Priest},
            new CDataSkillParam() {SkillNo = 2, Job = JobId.Priest},
            new CDataSkillParam() {SkillNo = 3, Job = JobId.Priest},
            new CDataSkillParam() {SkillNo = 4, Job = JobId.Priest},
            new CDataSkillParam() {SkillNo = 5, Job = JobId.Priest},
            new CDataSkillParam() {SkillNo = 6, Job = JobId.Priest},
            new CDataSkillParam() {SkillNo = 7, Job = JobId.Priest},
            new CDataSkillParam() {SkillNo = 8, Job = JobId.Priest},
            new CDataSkillParam() {SkillNo = 9, Job = JobId.Priest},
            new CDataSkillParam() {SkillNo = 10, Job = JobId.Priest},
            new CDataSkillParam() {SkillNo = 11, Job = JobId.Priest},
            new CDataSkillParam() {SkillNo = 12, Job = JobId.Priest},
            new CDataSkillParam() {SkillNo = 13, Job = JobId.Priest},
            new CDataSkillParam() {SkillNo = 113, Job = JobId.Priest},
            new CDataSkillParam() {SkillNo = 213, Job = JobId.Priest},
            new CDataSkillParam() {SkillNo = 105, Job = JobId.Priest},
            new CDataSkillParam() {SkillNo = 205, Job = JobId.Priest},
            new CDataSkillParam() {SkillNo = 104, Job = JobId.Priest},
            new CDataSkillParam() {SkillNo = 204, Job = JobId.Priest},
            new CDataSkillParam() {SkillNo = 102, Job = JobId.Priest},
            new CDataSkillParam() {SkillNo = 202, Job = JobId.Priest},
            // Shield Sage
            new CDataSkillParam() {SkillNo = 1, Job = JobId.ShieldSage},
            new CDataSkillParam() {SkillNo = 2, Job = JobId.ShieldSage},
            new CDataSkillParam() {SkillNo = 3, Job = JobId.ShieldSage},
            new CDataSkillParam() {SkillNo = 4, Job = JobId.ShieldSage},
            new CDataSkillParam() {SkillNo = 5, Job = JobId.ShieldSage},
            new CDataSkillParam() {SkillNo = 6, Job = JobId.ShieldSage},
            new CDataSkillParam() {SkillNo = 7, Job = JobId.ShieldSage},
            new CDataSkillParam() {SkillNo = 8, Job = JobId.ShieldSage},
            new CDataSkillParam() {SkillNo = 9, Job = JobId.ShieldSage},
            new CDataSkillParam() {SkillNo = 10, Job = JobId.ShieldSage},
            new CDataSkillParam() {SkillNo = 11, Job = JobId.ShieldSage},
            new CDataSkillParam() {SkillNo = 12, Job = JobId.ShieldSage},
            new CDataSkillParam() {SkillNo = 13, Job = JobId.ShieldSage},
            new CDataSkillParam() {SkillNo = 14, Job = JobId.ShieldSage},
            new CDataSkillParam() {SkillNo = 106, Job = JobId.ShieldSage},
            new CDataSkillParam() {SkillNo = 206, Job = JobId.ShieldSage},
            new CDataSkillParam() {SkillNo = 101, Job = JobId.ShieldSage},
            new CDataSkillParam() {SkillNo = 201, Job = JobId.ShieldSage},
            new CDataSkillParam() {SkillNo = 105, Job = JobId.ShieldSage},
            new CDataSkillParam() {SkillNo = 205, Job = JobId.ShieldSage},
            new CDataSkillParam() {SkillNo = 107, Job = JobId.ShieldSage},
            new CDataSkillParam() {SkillNo = 207, Job = JobId.ShieldSage},
            // Sorcerer
            new CDataSkillParam() {SkillNo = 1, Job = JobId.Sorcerer},
            new CDataSkillParam() {SkillNo = 2, Job = JobId.Sorcerer},
            new CDataSkillParam() {SkillNo = 3, Job = JobId.Sorcerer},
            new CDataSkillParam() {SkillNo = 4, Job = JobId.Sorcerer},
            new CDataSkillParam() {SkillNo = 5, Job = JobId.Sorcerer},
            new CDataSkillParam() {SkillNo = 6, Job = JobId.Sorcerer},
            new CDataSkillParam() {SkillNo = 7, Job = JobId.Sorcerer},
            new CDataSkillParam() {SkillNo = 8, Job = JobId.Sorcerer},
            new CDataSkillParam() {SkillNo = 9, Job = JobId.Sorcerer},
            new CDataSkillParam() {SkillNo = 10, Job = JobId.Sorcerer},
            new CDataSkillParam() {SkillNo = 11, Job = JobId.Sorcerer},
            new CDataSkillParam() {SkillNo = 12, Job = JobId.Sorcerer},
            new CDataSkillParam() {SkillNo = 13, Job = JobId.Sorcerer},
            new CDataSkillParam() {SkillNo = 14, Job = JobId.Sorcerer},
            new CDataSkillParam() {SkillNo = 110, Job = JobId.Sorcerer},
            new CDataSkillParam() {SkillNo = 210, Job = JobId.Sorcerer},
            new CDataSkillParam() {SkillNo = 102, Job = JobId.Sorcerer},
            new CDataSkillParam() {SkillNo = 202, Job = JobId.Sorcerer},
            new CDataSkillParam() {SkillNo = 104, Job = JobId.Sorcerer},
            new CDataSkillParam() {SkillNo = 204, Job = JobId.Sorcerer},
            new CDataSkillParam() {SkillNo = 105, Job = JobId.Sorcerer},
            new CDataSkillParam() {SkillNo = 205, Job = JobId.Sorcerer},
            // Warrior
            new CDataSkillParam() {SkillNo = 1, Job = JobId.Warrior},
            new CDataSkillParam() {SkillNo = 3, Job = JobId.Warrior},
            new CDataSkillParam() {SkillNo = 2, Job = JobId.Warrior},
            new CDataSkillParam() {SkillNo = 4, Job = JobId.Warrior},
            new CDataSkillParam() {SkillNo = 5, Job = JobId.Warrior},
            new CDataSkillParam() {SkillNo = 6, Job = JobId.Warrior},
            new CDataSkillParam() {SkillNo = 8, Job = JobId.Warrior},
            new CDataSkillParam() {SkillNo = 7, Job = JobId.Warrior},
            new CDataSkillParam() {SkillNo = 9, Job = JobId.Warrior},
            new CDataSkillParam() {SkillNo = 10, Job = JobId.Warrior},
            new CDataSkillParam() {SkillNo = 12, Job = JobId.Warrior},
            new CDataSkillParam() {SkillNo = 11, Job = JobId.Warrior},
            new CDataSkillParam() {SkillNo = 13, Job = JobId.Warrior},
            new CDataSkillParam() {SkillNo = 14, Job = JobId.Warrior},
            new CDataSkillParam() {SkillNo = 103, Job = JobId.Warrior},
            new CDataSkillParam() {SkillNo = 203, Job = JobId.Warrior},
            new CDataSkillParam() {SkillNo = 102, Job = JobId.Warrior},
            new CDataSkillParam() {SkillNo = 202, Job = JobId.Warrior},
            new CDataSkillParam() {SkillNo = 104, Job = JobId.Warrior},
            new CDataSkillParam() {SkillNo = 204, Job = JobId.Warrior},
            new CDataSkillParam() {SkillNo = 105, Job = JobId.Warrior},
            new CDataSkillParam() {SkillNo = 205, Job = JobId.Warrior},
            // Element Archer
            new CDataSkillParam() {SkillNo = 1, Job = JobId.ElementArcher},
            new CDataSkillParam() {SkillNo = 2, Job = JobId.ElementArcher},
            new CDataSkillParam() {SkillNo = 3, Job = JobId.ElementArcher},
            new CDataSkillParam() {SkillNo = 4, Job = JobId.ElementArcher},
            new CDataSkillParam() {SkillNo = 5, Job = JobId.ElementArcher},
            new CDataSkillParam() {SkillNo = 6, Job = JobId.ElementArcher},
            new CDataSkillParam() {SkillNo = 7, Job = JobId.ElementArcher},
            new CDataSkillParam() {SkillNo = 8, Job = JobId.ElementArcher},
            new CDataSkillParam() {SkillNo = 9, Job = JobId.ElementArcher},
            new CDataSkillParam() {SkillNo = 10, Job = JobId.ElementArcher},
            new CDataSkillParam() {SkillNo = 11, Job = JobId.ElementArcher},
            new CDataSkillParam() {SkillNo = 12, Job = JobId.ElementArcher},
            new CDataSkillParam() {SkillNo = 13, Job = JobId.ElementArcher},
            new CDataSkillParam() {SkillNo = 14, Job = JobId.ElementArcher},
            new CDataSkillParam() {SkillNo = 105, Job = JobId.ElementArcher},
            new CDataSkillParam() {SkillNo = 205, Job = JobId.ElementArcher},
            new CDataSkillParam() {SkillNo = 110, Job = JobId.ElementArcher},
            new CDataSkillParam() {SkillNo = 210, Job = JobId.ElementArcher},
            new CDataSkillParam() {SkillNo = 113, Job = JobId.ElementArcher},
            new CDataSkillParam() {SkillNo = 213, Job = JobId.ElementArcher},
            new CDataSkillParam() {SkillNo = 108, Job = JobId.ElementArcher},
            new CDataSkillParam() {SkillNo = 208, Job = JobId.ElementArcher},
            // Alchemist
            new CDataSkillParam() {SkillNo = 2, Job = JobId.Alchemist},
            new CDataSkillParam() {SkillNo = 1, Job = JobId.Alchemist},
            new CDataSkillParam() {SkillNo = 5, Job = JobId.Alchemist},
            new CDataSkillParam() {SkillNo = 6, Job = JobId.Alchemist},
            new CDataSkillParam() {SkillNo = 4, Job = JobId.Alchemist},
            new CDataSkillParam() {SkillNo = 3, Job = JobId.Alchemist},
            new CDataSkillParam() {SkillNo = 7, Job = JobId.Alchemist},
            new CDataSkillParam() {SkillNo = 8, Job = JobId.Alchemist},
            new CDataSkillParam() {SkillNo = 9, Job = JobId.Alchemist},
            new CDataSkillParam() {SkillNo = 10, Job = JobId.Alchemist},
            new CDataSkillParam() {SkillNo = 11, Job = JobId.Alchemist},
            new CDataSkillParam() {SkillNo = 12, Job = JobId.Alchemist},
            new CDataSkillParam() {SkillNo = 103, Job = JobId.Alchemist},
            new CDataSkillParam() {SkillNo = 203, Job = JobId.Alchemist},
            new CDataSkillParam() {SkillNo = 102, Job = JobId.Alchemist},
            new CDataSkillParam() {SkillNo = 202, Job = JobId.Alchemist},
            new CDataSkillParam() {SkillNo = 101, Job = JobId.Alchemist},
            new CDataSkillParam() {SkillNo = 201, Job = JobId.Alchemist},
            new CDataSkillParam() {SkillNo = 105, Job = JobId.Alchemist},
            new CDataSkillParam() {SkillNo = 205, Job = JobId.Alchemist},
            // Spirit Lance
            new CDataSkillParam() {SkillNo = 1, Job = JobId.SpiritLance},
            new CDataSkillParam() {SkillNo = 2, Job = JobId.SpiritLance},
            new CDataSkillParam() {SkillNo = 3, Job = JobId.SpiritLance},
            new CDataSkillParam() {SkillNo = 4, Job = JobId.SpiritLance},
            new CDataSkillParam() {SkillNo = 5, Job = JobId.SpiritLance},
            new CDataSkillParam() {SkillNo = 6, Job = JobId.SpiritLance},
            new CDataSkillParam() {SkillNo = 7, Job = JobId.SpiritLance},
            new CDataSkillParam() {SkillNo = 8, Job = JobId.SpiritLance},
            new CDataSkillParam() {SkillNo = 9, Job = JobId.SpiritLance},
            new CDataSkillParam() {SkillNo = 10, Job = JobId.SpiritLance},
            new CDataSkillParam() {SkillNo = 107, Job = JobId.SpiritLance},
            new CDataSkillParam() {SkillNo = 207, Job = JobId.SpiritLance},
            new CDataSkillParam() {SkillNo = 101, Job = JobId.SpiritLance},
            new CDataSkillParam() {SkillNo = 201, Job = JobId.SpiritLance},
            new CDataSkillParam() {SkillNo = 104, Job = JobId.SpiritLance},
            new CDataSkillParam() {SkillNo = 204, Job = JobId.SpiritLance},
            new CDataSkillParam() {SkillNo = 108, Job = JobId.SpiritLance},
            new CDataSkillParam() {SkillNo = 208, Job = JobId.SpiritLance},
            // High Scepter
            new CDataSkillParam() {SkillNo = 1, Job = JobId.HighScepter},
            new CDataSkillParam() {SkillNo = 2, Job = JobId.HighScepter},
            new CDataSkillParam() {SkillNo = 4, Job = JobId.HighScepter},
            new CDataSkillParam() {SkillNo = 3, Job = JobId.HighScepter},
            new CDataSkillParam() {SkillNo = 5, Job = JobId.HighScepter},
            new CDataSkillParam() {SkillNo = 6, Job = JobId.HighScepter},
            new CDataSkillParam() {SkillNo = 7, Job = JobId.HighScepter},
            new CDataSkillParam() {SkillNo = 8, Job = JobId.HighScepter}
        };

        public SkillGetAcquirableSkillListHandler(DdonGameServer server) : base(server)
        {
        }

        public override void Handle(GameClient client, StructurePacket<C2SSkillGetAcquirableSkillListReq> packet)
        {
            client.Send(new S2CSkillGetAcquirableSkillListRes(){
                SkillParamList = AllSkills
                    .Where(x => x.Job == packet.Structure.Job).ToList()
            });
        }
    }
}