using System.Collections.Generic;
using System.Linq;
using Arrowgene.Ddon.Server;
using Arrowgene.Ddon.Server.Network;
using Arrowgene.Ddon.Shared.Entity.PacketStructure;
using Arrowgene.Ddon.Shared.Entity.Structure;
using Arrowgene.Ddon.Shared.Network;
using Arrowgene.Logging;

namespace Arrowgene.Ddon.GameServer.Handler
{
    public class SkillGetAcquirableSkillListHandler : StructurePacketHandler<GameClient, C2SSkillGetAcquirableSkillListReq>
    {
        private static readonly ServerLogger Logger = LogProvider.Logger<ServerLogger>(typeof(SkillGetCurrentSetSkillListHandler));

        public static readonly List<CDataSkillParam> AllSkills = new List<CDataSkillParam>() {
            // Fighter
            new CDataSkillParam() {SkillNo = 1, Job = 1},
            new CDataSkillParam() {SkillNo = 2, Job = 1},
            new CDataSkillParam() {SkillNo = 3, Job = 1},
            new CDataSkillParam() {SkillNo = 4, Job = 1},
            new CDataSkillParam() {SkillNo = 5, Job = 1},
            new CDataSkillParam() {SkillNo = 6, Job = 1},
            new CDataSkillParam() {SkillNo = 7, Job = 1},
            new CDataSkillParam() {SkillNo = 8, Job = 1},
            new CDataSkillParam() {SkillNo = 9, Job = 1},
            new CDataSkillParam() {SkillNo = 10, Job = 1},
            new CDataSkillParam() {SkillNo = 11, Job = 1},
            new CDataSkillParam() {SkillNo = 12, Job = 1},
            new CDataSkillParam() {SkillNo = 13, Job = 1},
            new CDataSkillParam() {SkillNo = 14, Job = 1},
            new CDataSkillParam() {SkillNo = 104, Job = 1},
            new CDataSkillParam() {SkillNo = 204, Job = 1},
            new CDataSkillParam() {SkillNo = 102, Job = 1},
            new CDataSkillParam() {SkillNo = 202, Job = 1},
            new CDataSkillParam() {SkillNo = 108, Job = 1},
            new CDataSkillParam() {SkillNo = 208, Job = 1},
            new CDataSkillParam() {SkillNo = 103, Job = 1},
            new CDataSkillParam() {SkillNo = 203, Job = 1},
            // Seeker
            new CDataSkillParam() {SkillNo = 1, Job = 2},
            new CDataSkillParam() {SkillNo = 2, Job = 2},
            new CDataSkillParam() {SkillNo = 3, Job = 2},
            new CDataSkillParam() {SkillNo = 4, Job = 2},
            new CDataSkillParam() {SkillNo = 5, Job = 2},
            new CDataSkillParam() {SkillNo = 6, Job = 2},
            new CDataSkillParam() {SkillNo = 7, Job = 2},
            new CDataSkillParam() {SkillNo = 8, Job = 2},
            new CDataSkillParam() {SkillNo = 9, Job = 2},
            new CDataSkillParam() {SkillNo = 10, Job = 2},
            new CDataSkillParam() {SkillNo = 11, Job = 2},
            new CDataSkillParam() {SkillNo = 12, Job = 2},
            new CDataSkillParam() {SkillNo = 13, Job = 2},
            new CDataSkillParam() {SkillNo = 14, Job = 2},
            new CDataSkillParam() {SkillNo = 112, Job = 2},
            new CDataSkillParam() {SkillNo = 212, Job = 2},
            new CDataSkillParam() {SkillNo = 113, Job = 2},
            new CDataSkillParam() {SkillNo = 213, Job = 2},
            new CDataSkillParam() {SkillNo = 107, Job = 2},
            new CDataSkillParam() {SkillNo = 207, Job = 2},
            new CDataSkillParam() {SkillNo = 102, Job = 2},
            new CDataSkillParam() {SkillNo = 202, Job = 2},
            // Hunter
            new CDataSkillParam() {SkillNo = 1, Job = 3},
            new CDataSkillParam() {SkillNo = 2, Job = 3},
            new CDataSkillParam() {SkillNo = 4, Job = 3},
            new CDataSkillParam() {SkillNo = 3, Job = 3},
            new CDataSkillParam() {SkillNo = 5, Job = 3},
            new CDataSkillParam() {SkillNo = 6, Job = 3},
            new CDataSkillParam() {SkillNo = 7, Job = 3},
            new CDataSkillParam() {SkillNo = 8, Job = 3},
            new CDataSkillParam() {SkillNo = 9, Job = 3},
            new CDataSkillParam() {SkillNo = 10, Job = 3},
            new CDataSkillParam() {SkillNo = 11, Job = 3},
            new CDataSkillParam() {SkillNo = 12, Job = 3},
            new CDataSkillParam() {SkillNo = 13, Job = 3},
            new CDataSkillParam() {SkillNo = 14, Job = 3},
            new CDataSkillParam() {SkillNo = 101, Job = 3},
            new CDataSkillParam() {SkillNo = 201, Job = 3},
            new CDataSkillParam() {SkillNo = 106, Job = 3},
            new CDataSkillParam() {SkillNo = 206, Job = 3},
            new CDataSkillParam() {SkillNo = 108, Job = 3},
            new CDataSkillParam() {SkillNo = 208, Job = 3},
            new CDataSkillParam() {SkillNo = 110, Job = 3},
            new CDataSkillParam() {SkillNo = 210, Job = 3},
            // Priest
            new CDataSkillParam() {SkillNo = 1, Job = 4},
            new CDataSkillParam() {SkillNo = 2, Job = 4},
            new CDataSkillParam() {SkillNo = 3, Job = 4},
            new CDataSkillParam() {SkillNo = 4, Job = 4},
            new CDataSkillParam() {SkillNo = 5, Job = 4},
            new CDataSkillParam() {SkillNo = 6, Job = 4},
            new CDataSkillParam() {SkillNo = 7, Job = 4},
            new CDataSkillParam() {SkillNo = 8, Job = 4},
            new CDataSkillParam() {SkillNo = 9, Job = 4},
            new CDataSkillParam() {SkillNo = 10, Job = 4},
            new CDataSkillParam() {SkillNo = 11, Job = 4},
            new CDataSkillParam() {SkillNo = 12, Job = 4},
            new CDataSkillParam() {SkillNo = 13, Job = 4},
            new CDataSkillParam() {SkillNo = 113, Job = 4},
            new CDataSkillParam() {SkillNo = 213, Job = 4},
            new CDataSkillParam() {SkillNo = 105, Job = 4},
            new CDataSkillParam() {SkillNo = 205, Job = 4},
            new CDataSkillParam() {SkillNo = 104, Job = 4},
            new CDataSkillParam() {SkillNo = 204, Job = 4},
            new CDataSkillParam() {SkillNo = 102, Job = 4},
            new CDataSkillParam() {SkillNo = 202, Job = 4},
            // Shield Sage
            new CDataSkillParam() {SkillNo = 1, Job = 5},
            new CDataSkillParam() {SkillNo = 2, Job = 5},
            new CDataSkillParam() {SkillNo = 3, Job = 5},
            new CDataSkillParam() {SkillNo = 4, Job = 5},
            new CDataSkillParam() {SkillNo = 5, Job = 5},
            new CDataSkillParam() {SkillNo = 6, Job = 5},
            new CDataSkillParam() {SkillNo = 7, Job = 5},
            new CDataSkillParam() {SkillNo = 8, Job = 5},
            new CDataSkillParam() {SkillNo = 9, Job = 5},
            new CDataSkillParam() {SkillNo = 10, Job = 5},
            new CDataSkillParam() {SkillNo = 11, Job = 5},
            new CDataSkillParam() {SkillNo = 12, Job = 5},
            new CDataSkillParam() {SkillNo = 13, Job = 5},
            new CDataSkillParam() {SkillNo = 14, Job = 5},
            new CDataSkillParam() {SkillNo = 106, Job = 5},
            new CDataSkillParam() {SkillNo = 206, Job = 5},
            new CDataSkillParam() {SkillNo = 101, Job = 5},
            new CDataSkillParam() {SkillNo = 201, Job = 5},
            new CDataSkillParam() {SkillNo = 105, Job = 5},
            new CDataSkillParam() {SkillNo = 205, Job = 5},
            new CDataSkillParam() {SkillNo = 107, Job = 5},
            new CDataSkillParam() {SkillNo = 207, Job = 5},
            // Sorcerer
            new CDataSkillParam() {SkillNo = 1, Job = 6},
            new CDataSkillParam() {SkillNo = 2, Job = 6},
            new CDataSkillParam() {SkillNo = 3, Job = 6},
            new CDataSkillParam() {SkillNo = 4, Job = 6},
            new CDataSkillParam() {SkillNo = 5, Job = 6},
            new CDataSkillParam() {SkillNo = 6, Job = 6},
            new CDataSkillParam() {SkillNo = 7, Job = 6},
            new CDataSkillParam() {SkillNo = 8, Job = 6},
            new CDataSkillParam() {SkillNo = 9, Job = 6},
            new CDataSkillParam() {SkillNo = 10, Job = 6},
            new CDataSkillParam() {SkillNo = 11, Job = 6},
            new CDataSkillParam() {SkillNo = 12, Job = 6},
            new CDataSkillParam() {SkillNo = 13, Job = 6},
            new CDataSkillParam() {SkillNo = 14, Job = 6},
            new CDataSkillParam() {SkillNo = 110, Job = 6},
            new CDataSkillParam() {SkillNo = 210, Job = 6},
            new CDataSkillParam() {SkillNo = 102, Job = 6},
            new CDataSkillParam() {SkillNo = 202, Job = 6},
            new CDataSkillParam() {SkillNo = 104, Job = 6},
            new CDataSkillParam() {SkillNo = 204, Job = 6},
            new CDataSkillParam() {SkillNo = 105, Job = 6},
            new CDataSkillParam() {SkillNo = 205, Job = 6},
            // Warrior
            new CDataSkillParam() {SkillNo = 1, Job = 7},
            new CDataSkillParam() {SkillNo = 3, Job = 7},
            new CDataSkillParam() {SkillNo = 2, Job = 7},
            new CDataSkillParam() {SkillNo = 4, Job = 7},
            new CDataSkillParam() {SkillNo = 5, Job = 7},
            new CDataSkillParam() {SkillNo = 6, Job = 7},
            new CDataSkillParam() {SkillNo = 8, Job = 7},
            new CDataSkillParam() {SkillNo = 7, Job = 7},
            new CDataSkillParam() {SkillNo = 9, Job = 7},
            new CDataSkillParam() {SkillNo = 10, Job = 7},
            new CDataSkillParam() {SkillNo = 12, Job = 7},
            new CDataSkillParam() {SkillNo = 11, Job = 7},
            new CDataSkillParam() {SkillNo = 13, Job = 7},
            new CDataSkillParam() {SkillNo = 14, Job = 7},
            new CDataSkillParam() {SkillNo = 103, Job = 7},
            new CDataSkillParam() {SkillNo = 203, Job = 7},
            new CDataSkillParam() {SkillNo = 102, Job = 7},
            new CDataSkillParam() {SkillNo = 202, Job = 7},
            new CDataSkillParam() {SkillNo = 104, Job = 7},
            new CDataSkillParam() {SkillNo = 204, Job = 7},
            new CDataSkillParam() {SkillNo = 105, Job = 7},
            new CDataSkillParam() {SkillNo = 205, Job = 7},
            // Element Archer
            new CDataSkillParam() {SkillNo = 1, Job = 8},
            new CDataSkillParam() {SkillNo = 2, Job = 8},
            new CDataSkillParam() {SkillNo = 3, Job = 8},
            new CDataSkillParam() {SkillNo = 4, Job = 8},
            new CDataSkillParam() {SkillNo = 5, Job = 8},
            new CDataSkillParam() {SkillNo = 6, Job = 8},
            new CDataSkillParam() {SkillNo = 7, Job = 8},
            new CDataSkillParam() {SkillNo = 8, Job = 8},
            new CDataSkillParam() {SkillNo = 9, Job = 8},
            new CDataSkillParam() {SkillNo = 10, Job = 8},
            new CDataSkillParam() {SkillNo = 11, Job = 8},
            new CDataSkillParam() {SkillNo = 12, Job = 8},
            new CDataSkillParam() {SkillNo = 13, Job = 8},
            new CDataSkillParam() {SkillNo = 14, Job = 8},
            new CDataSkillParam() {SkillNo = 105, Job = 8},
            new CDataSkillParam() {SkillNo = 205, Job = 8},
            new CDataSkillParam() {SkillNo = 110, Job = 8},
            new CDataSkillParam() {SkillNo = 210, Job = 8},
            new CDataSkillParam() {SkillNo = 113, Job = 8},
            new CDataSkillParam() {SkillNo = 213, Job = 8},
            new CDataSkillParam() {SkillNo = 108, Job = 8},
            new CDataSkillParam() {SkillNo = 208, Job = 8},
            // Alchemist
            new CDataSkillParam() {SkillNo = 2, Job = 9},
            new CDataSkillParam() {SkillNo = 1, Job = 9},
            new CDataSkillParam() {SkillNo = 5, Job = 9},
            new CDataSkillParam() {SkillNo = 6, Job = 9},
            new CDataSkillParam() {SkillNo = 4, Job = 9},
            new CDataSkillParam() {SkillNo = 3, Job = 9},
            new CDataSkillParam() {SkillNo = 7, Job = 9},
            new CDataSkillParam() {SkillNo = 8, Job = 9},
            new CDataSkillParam() {SkillNo = 9, Job = 9},
            new CDataSkillParam() {SkillNo = 10, Job = 9},
            new CDataSkillParam() {SkillNo = 11, Job = 9},
            new CDataSkillParam() {SkillNo = 12, Job = 9},
            new CDataSkillParam() {SkillNo = 103, Job = 9},
            new CDataSkillParam() {SkillNo = 203, Job = 9},
            new CDataSkillParam() {SkillNo = 102, Job = 9},
            new CDataSkillParam() {SkillNo = 202, Job = 9},
            new CDataSkillParam() {SkillNo = 101, Job = 9},
            new CDataSkillParam() {SkillNo = 201, Job = 9},
            new CDataSkillParam() {SkillNo = 105, Job = 9},
            new CDataSkillParam() {SkillNo = 205, Job = 9},
            // Spirit Lance
            new CDataSkillParam() {SkillNo = 1, Job = 10},
            new CDataSkillParam() {SkillNo = 2, Job = 10},
            new CDataSkillParam() {SkillNo = 3, Job = 10},
            new CDataSkillParam() {SkillNo = 4, Job = 10},
            new CDataSkillParam() {SkillNo = 5, Job = 10},
            new CDataSkillParam() {SkillNo = 6, Job = 10},
            new CDataSkillParam() {SkillNo = 7, Job = 10},
            new CDataSkillParam() {SkillNo = 8, Job = 10},
            new CDataSkillParam() {SkillNo = 9, Job = 10},
            new CDataSkillParam() {SkillNo = 10, Job = 10},
            new CDataSkillParam() {SkillNo = 107, Job = 10},
            new CDataSkillParam() {SkillNo = 207, Job = 10},
            new CDataSkillParam() {SkillNo = 101, Job = 10},
            new CDataSkillParam() {SkillNo = 201, Job = 10},
            new CDataSkillParam() {SkillNo = 104, Job = 10},
            new CDataSkillParam() {SkillNo = 204, Job = 10},
            new CDataSkillParam() {SkillNo = 108, Job = 10},
            new CDataSkillParam() {SkillNo = 208, Job = 10},
            // High Scepter
            new CDataSkillParam() {SkillNo = 1, Job = 11},
            new CDataSkillParam() {SkillNo = 2, Job = 11},
            new CDataSkillParam() {SkillNo = 4, Job = 11},
            new CDataSkillParam() {SkillNo = 3, Job = 11},
            new CDataSkillParam() {SkillNo = 5, Job = 11},
            new CDataSkillParam() {SkillNo = 6, Job = 11},
            new CDataSkillParam() {SkillNo = 7, Job = 11},
            new CDataSkillParam() {SkillNo = 8, Job = 11}
        };

        public SkillGetAcquirableSkillListHandler(DdonGameServer server) : base(server)
        {
        }

        public override void Handle(GameClient client, StructurePacket<C2SSkillGetAcquirableSkillListReq> packet)
        {
            client.Send(new S2CSkillGetAcquirableSkillListRes(){
                SkillParamList = AllSkills
                    .Where(x => x.Job == packet.Structure.Job).ToList()
            });
        }
    }
}