volumes:
  ddon-psql-data:

services:
  db:
    container_name: db
    image: postgres:17
    ports:
      - "5432:5432"
    restart: no
    volumes:
      - ddon-psql-data:/var/lib/postgresql/data
      - ../../Arrowgene.Ddon.Database/Files/Database/Script/schema_postgres.sql:/docker-entrypoint-initdb.d/schema_postgres.sql:ro
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_INITDB_ARGS=--auth=scram-sha-256 --lc-numeric=en_US.UTF-8
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 10s
      timeout: 1s
      retries: 3
      
  pgloader:
    image: dimitri/pgloader:latest
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../../Arrowgene.Ddon.Cli/bin/Debug/net9.0/Files/Database/db.sqlite:/db.sqlite:ro
      - ./pgloader.load:/pgloader.load:ro
    entrypoint: pgloader
#    command: sqlite:///db.sqlite postgresql://root:root@psql:5432/postgres
    command: -v /pgloader.load
