CREATE TABLE ddon_job_emblem (
	"character_id"	     INTEGER NOT NULL,
	"job_id"	         INTEGER NOT NULL,
    "emblem_level"       SMALLINT NOT NULL,
    "emblem_points_used" SMALLINT NOT NULL,
    "physical_attack"    SMALLINT NOT NULL,
    "magick_attack"      SMALLINT NOT NULL,
    "physical_defense"   SMALLINT NOT NULL,
    "magick_defense"     SMALLINT NOT NULL,
    "max_hp"             SMALLINT NOT NULL,
    "max_stamina"        SMALLINT NOT NULL,
    "healing_power"      SMALLINT NOT NULL,
    "endurance"          SMALLINT NOT NULL,
    "blow_power"         SMALLINT NOT NULL,
    "chance_attack"      SMALLINT NOT NULL,
    "exhaust_attack"     SMALLINT NOT NULL,
    "knockout_power"     SMALLINT NOT NULL,
    "fire_resist"        SMALLINT NOT NULL,
    "ice_resist"         SMALLINT NOT NULL,
    "thunder_resist"     SMALLINT NOT NULL,
    "holy_resist"        SMALLINT NOT NULL,
    "dark_resist"        SMALLINT NOT NULL,
    CONSTRAINT pk_ddon_job_emblem PRIMARY KEY ("character_id", "job_id"),
    CONSTRAINT fk_ddon_job_emblem_character_id FOREIGN KEY ("character_id") REFERENCES "ddon_character" ("character_id") ON DELETE CASCADE
);
